const defaultPlayers = Array.from({ length: 16 }, (_, index) => ({
  id: `p${index + 1}`,
  number: index + 1,
  name: `Player ${index + 1}`,
}));

let players = [...defaultPlayers];

const translations = {
  "en-US": {
    appTitle: "Handball Scout Pad",
    heroEyebrow: "Live handball scouting",
    heroTitle: "Track primary actions. Derive the rest.",
    heroCopy: "A tablet-first entry surface built around player selection, action buttons, and context prompts.",
    playCountLabel: "Plays",
    eventCountLabel: "Derived events",
    entryPadTitle: "Entry Pad",
    resetFlow: "Reset flow",
    startActionTitle: "Start Action",
    startActionCopy: "All primary actions stay available from the first screen.",
    guidedFlow: "Guided Flow",
    guidedFlowCopy: "Pick an action to start the staged entry flow.",
    waitingForAction: "Waiting for action",
    selectPrimaryAction: "Select a primary action above to begin.",
    back: "Back",
    next: "Next",
    recordPlay: "Record play",
    saveChanges: "Save changes",
    liveStateTitle: "Live match state",
    addDemoSequence: "Add demo sequence",
    recordedPlaysTitle: "Recorded plays",
    derivedEventsTitle: "Derived events",
    autoGenerated: "Auto-generated",
    noPlaysYet: "No plays yet",
    playLogEmpty: "Record a play to start building the match timeline.",
    eventLogEmpty: "Derived stat events will appear here.",
    settingsTitle: "Flow settings",
    settingsCopy: "Choose which context steps should appear for each action.",
    openSettings: "Open settings",
    closeSettings: "Close settings",
    importTitle: "Import Profixio timeline",
    importCopy: "Upload a Profixio timeline PDF and import the selected side into the app.",
    openImport: "Open import dialog",
    closeImport: "Close import dialog",
    openPlayerStats: "Open player stats",
    closePlayerStats: "Close player stats",
    playerStatsTitle: "Player stats",
    playerStatsCopy: "View sortable live stats per player.",
    playerStatsEmpty: "No player stats available yet.",
    playerStatsPlayer: "Player",
    playerStatsShots: "Shots",
    playerStatsGoals: "Goals",
    playerStatsMisses: "Misses",
    playerStatsEfficiency: "Eff %",
    playerStatsShotsOnGoal: "On goal",
    playerStatsSaves: "Saves",
    playerStatsSavePercentage: "Save %",
    playerStatsPenalties: "Pens",
    playerStatsPenaltyGoals: "Pen goals",
    playerStatsPenaltyMisses: "Pen miss",
    playerStatsPenaltyEfficiency: "Pen %",
    playerStatsTechFaults: "Tech",
    playerStatsSuspensions: "Susp",
    playerStatsWarnings: "Warn",
    importPdfLabel: "Imported PDF",
    importPdfNote: "Upload a Profixio timeline PDF and choose which side to import.",
    importTeamLabel: "Team side",
    importTeamHome: "Home team",
    importTeamAway: "Away team",
    importPdfButton: "Import PDF",
    importEmpty: "No import loaded.",
    importSuccess: "Imported {plays} plays and {events} events from {match}.",
    importErrorPrefix: "Import error: {message}",
    importPdfNoFile: "Choose a PDF file first.",
    importPdfUnsupported: "This browser does not support local PDF decompression for import.",
    importPdfTeamsNotFound: "Could not identify home and away teams from the PDF.",
    importPdfNoRows: "No timeline rows found for {team}.",
    importPdfCandidates: "Found title rows:\n{rows}",
    importPdfParsedRows: "Parsed timeline rows:\n{rows}",
    importPdfDebug: "PDF debug:\n{debug}",
    importPdfSuccessDebug: "Imported {plays} plays and {events} events from {match}.\n\nPDF debug:\n{debug}",
    modeEditing: "Editing existing play",
    modeCreating: "Creating new play",
    notSelected: "Not selected",
    noContextSelected: "No context selected",
    stepOf: "Step {current} of {total}",
    choosePlayer: "Choose player",
    choosePlayerCopy: "Select the player responsible for this action.",
    settingsGroupCopy: "Choose which context steps should appear in the guided flow.",
    presetsTitle: "Presets",
    presetsCopy: "Apply a saved setup for context detail levels.",
    presetDetailed: "Detailed",
    presetSimple: "Simple",
    displaySettingsTitle: "Display",
    displaySettingsCopy: "Control how actions are presented in the entry pad.",
    showActionIcons: "Show action icons",
    autoRecordLastDetail: "Auto record on last detail",
    toggleOn: "On",
    toggleOff: "Off",
    noConfigurableContext: "No configurable context groups available.",
    edit: "Edit",
    editing: "Editing",
    delete: "Delete",
    flowSuffix: "flow",
    captureContext: "Capture {label} before recording the play.",
    metricTotalShots: "Total shots",
    metricTotalShotsCaption: "All registered shot attempts including penalties",
    metricGoals: "Goals",
    metricGoalsCaption: "Scoring events from shots and penalties",
    metricMisses: "Misses",
    metricMissesCaption: "Off-target or missed attempts",
    metricShotsOnGoal: "Shots on goal",
    metricShotsOnGoalCaption: "Goals and saved on-target shots",
    metricSaves: "Saves",
    metricSavesCaption: "Goalkeeper saves against shots on goal",
    metricSavePercentage: "Save %",
    metricSavePercentageCaption: "Saves divided by shots on goal",
    metricGroupShooting: "Shooting",
    metricGroupGoalkeeping: "Shots on goal",
    metricGroupPenalties: "Penalties",
    metricGroupDiscipline: "Discipline",
    metricShotEfficiency: "Efficiency",
    metricShotEfficiencyCaption: "Goals divided by total shots",
    metricPenalties: "Penalties",
    metricPenaltiesCaption: "Registered 7m attempts",
    metricPenaltyGoals: "Penalty goals",
    metricPenaltyGoalsCaption: "Goals scored from 7m",
    metricPenaltyMisses: "Penalty misses",
    metricPenaltyMissesCaption: "Saved or missed 7m attempts",
    metricPenaltyEfficiency: "Penalty efficiency",
    metricPenaltyEfficiencyCaption: "Penalty goals divided by penalties",
    metricTechFaults: "Technical faults",
    metricTechFaultsCaption: "Turnovers and handling faults",
    metricSuspensions: "Suspensions",
    metricSuspensionsCaption: "2-minute suspensions",
    metricWarnings: "Warnings",
    metricWarningsCaption: "Yellow cards",
    summaryMode: "MODE",
    summaryPlayer: "PLAYER",
    summaryAction: "ACTION",
    summaryContext: "CONTEXT",
    action: {
      SHOT: { label: "Shot", description: "Creates shot and outcome events" },
      PENALTY: { label: "Penalty", description: "Records a 7m attempt and outcome" },
      SAVE: { label: "Save", description: "Manual goalkeeper save entry" },
      MISS: { label: "Miss", description: "Manual missed attempt" },
      TECH_FAULT: { label: "Tech Fault", description: "Turnover or handling fault" },
      STEAL: { label: "Steal", description: "Defensive possession win" },
      BLOCK: { label: "Block", description: "Blocked attacking action" },
      CARD: { label: "Card", description: "Warning or discipline event" },
      SUSPENSION: { label: "Suspension", description: "Timed exclusion" },
    },
    contextLabel: {
      height: "Height",
      location: "Location",
      outcome: "Outcome",
      assistPlayerId: "Assist",
      cardType: "Card type",
      duration: "Duration",
    },
    optionLabel: {
      HIGH: "High",
      LOW: "Low",
      WING: "Wing",
      BACKCOURT: "Backcourt",
      LINE: "Line",
      BREAKTHROUGH: "Breakthrough",
      FAST_BREAK: "Fast break",
      PENALTY: "Penalty",
      GOAL: "Goal",
      SAVE: "Save",
      MISS: "Miss",
      BLOCK: "Block",
      NONE: "No assist",
      YELLOW: "Yellow",
      RED: "Red",
      "2 MIN": "2 min",
    },
  },
  "sv-SE": {
    appTitle: "Handboll Scout Pad",
    heroEyebrow: "Live scouting i handboll",
    heroTitle: "Registrera grundhändelser. Härled resten.",
    heroCopy: "En surfplatteanpassad registreringsyta byggd kring spelare, händelseknappar och kontextsteg.",
    playCountLabel: "Spel",
    eventCountLabel: "Härledda händelser",
    entryPadTitle: "Inmatning",
    resetFlow: "Återställ",
    startActionTitle: "Starta händelse",
    startActionCopy: "Alla primära händelser finns tillgängliga direkt från första vyn.",
    guidedFlow: "Stegvis flöde",
    guidedFlowCopy: "Välj en händelse för att starta det stegvisa flödet.",
    waitingForAction: "Väntar på händelse",
    selectPrimaryAction: "Välj en primär händelse ovan för att börja.",
    back: "Tillbaka",
    next: "Nästa",
    recordPlay: "Registrera",
    saveChanges: "Spara ändringar",
    liveStateTitle: "Matchläge live",
    addDemoSequence: "Lägg till demo",
    recordedPlaysTitle: "Registrerade spel",
    derivedEventsTitle: "Härledda händelser",
    autoGenerated: "Automatiskt skapade",
    noPlaysYet: "Inga spel ännu",
    playLogEmpty: "Registrera ett spel för att börja bygga matchtidslinjen.",
    eventLogEmpty: "Härledda statistik-händelser visas här.",
    settingsTitle: "Flödesinställningar",
    settingsCopy: "Välj vilka kontextsteg som ska visas för varje händelse.",
    openSettings: "Öppna inställningar",
    closeSettings: "Stäng inställningar",
    importTitle: "Importera Profixio-tidslinje",
    importCopy: "Ladda upp en Profixio-tidslinje som PDF och importera vald sida i appen.",
    openImport: "Öppna importdialog",
    closeImport: "Stäng importdialog",
    openPlayerStats: "Öppna spelarstatistik",
    closePlayerStats: "Stäng spelarstatistik",
    playerStatsTitle: "Spelarstatistik",
    playerStatsCopy: "Visa sorterbar live-statistik per spelare.",
    playerStatsEmpty: "Ingen spelarstatistik tillgänglig ännu.",
    playerStatsPlayer: "Spelare",
    playerStatsShots: "Skott",
    playerStatsGoals: "Mål",
    playerStatsMisses: "Missar",
    playerStatsEfficiency: "Eff %",
    playerStatsShotsOnGoal: "På mål",
    playerStatsSaves: "Räddn",
    playerStatsSavePercentage: "Rädd %",
    playerStatsPenalties: "Straff",
    playerStatsPenaltyGoals: "Str mål",
    playerStatsPenaltyMisses: "Str miss",
    playerStatsPenaltyEfficiency: "Str %",
    playerStatsTechFaults: "Tek",
    playerStatsSuspensions: "Utv",
    playerStatsWarnings: "Var",
    importPdfLabel: "Importerad PDF",
    importPdfNote: "Ladda upp en Profixio-tidslinje som PDF och välj vilken sida som ska importeras.",
    importTeamLabel: "Lagsida",
    importTeamHome: "Hemmalag",
    importTeamAway: "Bortalag",
    importPdfButton: "Importera PDF",
    importEmpty: "Ingen import inläst.",
    importSuccess: "Importerade {plays} spel och {events} händelser från {match}.",
    importErrorPrefix: "Importfel: {message}",
    importPdfNoFile: "Välj en PDF-fil först.",
    importPdfUnsupported: "Den här webbläsaren stöder inte lokal PDF-dekomprimering för import.",
    importPdfTeamsNotFound: "Kunde inte identifiera hemma- och bortalag i PDF-filen.",
    importPdfNoRows: "Hittade inga tidslinjerader för {team}.",
    importPdfCandidates: "Hittade titelrader:\n{rows}",
    importPdfParsedRows: "Parsade tidslinjerader:\n{rows}",
    importPdfDebug: "PDF-debug:\n{debug}",
    importPdfSuccessDebug: "Importerade {plays} spel och {events} händelser från {match}.\n\nPDF-debug:\n{debug}",
    modeEditing: "Redigerar befintligt spel",
    modeCreating: "Skapar nytt spel",
    notSelected: "Inte vald",
    noContextSelected: "Ingen kontext vald",
    stepOf: "Steg {current} av {total}",
    choosePlayer: "Välj spelare",
    choosePlayerCopy: "Välj spelaren som ansvarar för händelsen.",
    settingsGroupCopy: "Välj vilka kontextsteg som ska visas i det stegvisa flödet.",
    presetsTitle: "Förval",
    presetsCopy: "Använd en sparad uppsättning för detaljnivå i kontexten.",
    presetDetailed: "Detaljerad",
    presetSimple: "Enkel",
    displaySettingsTitle: "Visning",
    displaySettingsCopy: "Styr hur händelser visas i inmatningsytan.",
    showActionIcons: "Visa händelseikoner",
    autoRecordLastDetail: "Spara automatiskt vid sista detaljen",
    toggleOn: "På",
    toggleOff: "Av",
    noConfigurableContext: "Inga konfigurerbara kontextsteg finns.",
    edit: "Redigera",
    editing: "Redigerar",
    delete: "Ta bort",
    flowSuffix: "flöde",
    captureContext: "Registrera {label} innan spelet sparas.",
    metricTotalShots: "Totala skott",
    metricTotalShotsCaption: "Alla registrerade avslut inklusive straffar",
    metricGoals: "Mål",
    metricGoalsCaption: "Mål från skott och straffar",
    metricMisses: "Missar",
    metricMissesCaption: "Missade eller utanför avslut",
    metricShotsOnGoal: "Skott på mål",
    metricShotsOnGoalCaption: "Mål och räddade avslut på mål",
    metricSaves: "Räddningar",
    metricSavesCaption: "Målvaktsräddningar på skott på mål",
    metricSavePercentage: "Räddningsprocent",
    metricSavePercentageCaption: "Räddningar dividerat med skott på mål",
    metricGroupShooting: "Avslut",
    metricGroupGoalkeeping: "Skott på mål",
    metricGroupPenalties: "Straffar",
    metricGroupDiscipline: "Disciplin",
    metricShotEfficiency: "Effektivitet",
    metricShotEfficiencyCaption: "Mål dividerat med totala skott",
    metricPenalties: "Straffar",
    metricPenaltiesCaption: "Registrerade 7 m-försök",
    metricPenaltyGoals: "Straffmål",
    metricPenaltyGoalsCaption: "Mål på 7 m",
    metricPenaltyMisses: "Straffmiss",
    metricPenaltyMissesCaption: "Missade eller räddade 7 m",
    metricPenaltyEfficiency: "Straffeffektivitet",
    metricPenaltyEfficiencyCaption: "Straffmål dividerat med antal straffar",
    metricTechFaults: "Tekniska fel",
    metricTechFaultsCaption: "Bolltapp och tekniska fel",
    metricSuspensions: "Utvisningar",
    metricSuspensionsCaption: "Tvåminutersutvisningar",
    metricWarnings: "Varningar",
    metricWarningsCaption: "Gula kort",
    summaryMode: "LÄGE",
    summaryPlayer: "SPELARE",
    summaryAction: "HÄNDELSE",
    summaryContext: "KONTEXT",
    action: {
      SHOT: { label: "Skott", description: "Skapar skott- och utfallshändelser" },
      PENALTY: { label: "Straff", description: "Registrerar ett 7 m-försök och utfall" },
      SAVE: { label: "Räddning", description: "Manuell registrering av målvaktsräddning" },
      MISS: { label: "Miss", description: "Manuellt registrerat missat avslut" },
      TECH_FAULT: { label: "Tekniskt fel", description: "Bolltapp eller tekniskt fel" },
      STEAL: { label: "Stöld", description: "Defensivt bollvinst" },
      BLOCK: { label: "Block", description: "Blockerad anfallshändelse" },
      CARD: { label: "Kort", description: "Varning eller disciplinhändelse" },
      SUSPENSION: { label: "Utvisning", description: "Tidsbegränsad utvisning" },
    },
    contextLabel: {
      height: "Höjd",
      location: "Position",
      outcome: "Utfall",
      assistPlayerId: "Assist",
      cardType: "Korttyp",
      duration: "Längd",
    },
    optionLabel: {
      HIGH: "Hög",
      LOW: "Låg",
      WING: "Kant",
      BACKCOURT: "Nio meter",
      LINE: "Linje",
      BREAKTHROUGH: "Genombrott",
      FAST_BREAK: "Kontring",
      PENALTY: "Straff",
      GOAL: "Mål",
      SAVE: "Räddning",
      MISS: "Miss",
      BLOCK: "Block",
      NONE: "Ingen assist",
      YELLOW: "Gult",
      RED: "Rött",
      "2 MIN": "2 min",
    },
  },
};

const actionIcons = {
  SHOT: "◎",
  PENALTY: "7m",
  SAVE: "◐",
  MISS: "○",
  TECH_FAULT: "!",
  STEAL: "↺",
  BLOCK: "■",
  CARD: "▮",
  SUSPENSION: "2'",
};

const actionDefinitions = [
  { id: "SHOT", label: "Shot", description: "Creates shot and outcome events" },
  { id: "PENALTY", label: "Penalty", description: "Records a 7m attempt and outcome" },
  { id: "SAVE", label: "Save", description: "Manual goalkeeper save entry" },
  { id: "MISS", label: "Miss", description: "Manual missed attempt" },
  { id: "TECH_FAULT", label: "Tech Fault", description: "Turnover or handling fault" },
  { id: "STEAL", label: "Steal", description: "Defensive possession win" },
  { id: "BLOCK", label: "Block", description: "Blocked attacking action" },
  { id: "CARD", label: "Card", description: "Warning or discipline event" },
  { id: "SUSPENSION", label: "Suspension", description: "Timed exclusion" },
];

const contextDefinitions = {
  SHOT: [
    { key: "height", label: "Height", options: ["HIGH", "LOW"] },
    { key: "location", label: "Location", options: ["WING", "BACKCOURT", "LINE", "BREAKTHROUGH", "FAST_BREAK"] },
    { key: "outcome", label: "Outcome", options: ["GOAL", "SAVE", "MISS", "BLOCK"] },
  ],
  PENALTY: [
    { key: "height", label: "Height", options: ["HIGH", "LOW"] },
    { key: "outcome", label: "Outcome", options: ["GOAL", "SAVE", "MISS"] },
  ],
  SAVE: [
    { key: "height", label: "Shot height", options: ["HIGH", "LOW"] },
    { key: "location", label: "Shot source", options: ["WING", "BACKCOURT", "LINE", "BREAKTHROUGH", "PENALTY", "FAST_BREAK"] },
  ],
  MISS: [
    { key: "height", label: "Shot height", options: ["HIGH", "LOW"] },
    { key: "location", label: "Shot source", options: ["WING", "BACKCOURT", "LINE", "BREAKTHROUGH", "PENALTY", "FAST_BREAK"] },
  ],
  CARD: [
    { key: "cardType", label: "Card type", options: ["YELLOW", "RED"] },
  ],
  SUSPENSION: [
    { key: "duration", label: "Duration", options: ["2 MIN"] },
  ],
};

const contextSettings = Object.fromEntries(
  Object.entries(contextDefinitions).map(([actionId, groups]) => [
    actionId,
    Object.fromEntries(groups.map((group) => [group.key, true])),
  ]),
);

contextSettings.SHOT.assistPlayerId = true;

const settingsPresets = {
  detailed: {
    SHOT: { height: true, location: true, outcome: true, assistPlayerId: true },
    PENALTY: { height: true, outcome: true },
    SAVE: { height: true, location: true },
    MISS: { height: true, location: true },
    CARD: { cardType: true },
    SUSPENSION: { duration: true },
  },
  simple: {
    SHOT: { height: false, location: false, outcome: true, assistPlayerId: false },
    PENALTY: { height: false, outcome: true },
    SAVE: { height: false, location: false },
    MISS: { height: false, location: false },
    CARD: { cardType: true },
    SUSPENSION: { duration: true },
  },
};

Object.entries(settingsPresets.simple).forEach(([actionId, config]) => {
  Object.entries(config).forEach(([key, value]) => {
    if (contextSettings[actionId] && key in contextSettings[actionId]) {
      contextSettings[actionId][key] = value;
    }
  });
});

const state = {
  language: "sv-SE",
  showActionIcons: true,
  autoRecordLastDetail: true,
  selectedPlayerId: null,
  selectedActionId: null,
  context: {},
  editingPlayId: null,
  currentStageIndex: 0,
  contextSettings,
  plays: [],
  events: [],
  importStatus: null,
  playerStatsSort: { key: "goals", direction: "desc" },
};

const actionGrid = document.querySelector("#action-grid");
const actionStepCard = document.querySelector("#action-step-card");
const flowTitle = document.querySelector("#flow-title");
const flowCopy = document.querySelector("#flow-copy");
const flowProgress = document.querySelector("#flow-progress");
const flowStageLabel = document.querySelector("#flow-stage-label");
const flowCard = document.querySelector("#flow-card");
const stageHost = document.querySelector("#stage-host");
const selectionSummary = document.querySelector("#selection-summary");
const backStepButton = document.querySelector("#back-step");
const nextStepButton = document.querySelector("#next-step");
const commitButton = document.querySelector("#commit-play");
const playLog = document.querySelector("#play-log");
const eventLog = document.querySelector("#event-log");
const toggleSettingsButton = document.querySelector("#toggle-settings");
const closeSettingsButton = document.querySelector("#close-settings");
const settingsDialog = document.querySelector("#settings-dialog");
const settingsPanel = document.querySelector("#settings-panel");
const toggleImportButton = document.querySelector("#toggle-import");
const closeImportButton = document.querySelector("#close-import");
const importDialog = document.querySelector("#import-dialog");
const togglePlayerStatsButton = document.querySelector("#toggle-player-stats");
const closePlayerStatsButton = document.querySelector("#close-player-stats");
const playerStatsDialog = document.querySelector("#player-stats-dialog");
const playerStatsTableHost = document.querySelector("#player-stats-table-host");
const importFile = document.querySelector("#import-file");
const importTeamSide = document.querySelector("#import-team-side");
const importPdfButton = document.querySelector("#import-pdf");
const importStatus = document.querySelector("#import-status");
const playCount = document.querySelector("#play-count");
const eventCount = document.querySelector("#event-count");
const metricsGrid = document.querySelector("#metrics-grid");
const lastPlayLabel = document.querySelector("#last-play-label");
const langEnButton = document.querySelector("#lang-en");
const langSvButton = document.querySelector("#lang-sv");

let lastFlowViewportKey = "";

document.querySelector("#reset-flow").addEventListener("click", resetFlow);
document.querySelector("#commit-play").addEventListener("click", commitPlay);
document.querySelector("#seed-demo").addEventListener("click", seedDemoSequence);
toggleSettingsButton.addEventListener("click", openSettingsDialog);
closeSettingsButton.addEventListener("click", closeSettingsDialog);
toggleImportButton.addEventListener("click", openImportDialog);
closeImportButton.addEventListener("click", closeImportDialog);
togglePlayerStatsButton.addEventListener("click", openPlayerStatsDialog);
closePlayerStatsButton.addEventListener("click", closePlayerStatsDialog);
backStepButton.addEventListener("click", goToPreviousStage);
nextStepButton.addEventListener("click", goToNextStage);
settingsDialog.addEventListener("close", renderSettingsButtonState);
settingsDialog.addEventListener("click", handleDialogBackdropClick);
importDialog.addEventListener("close", renderImportButtonState);
importDialog.addEventListener("click", handleDialogBackdropClick);
playerStatsDialog.addEventListener("close", renderPlayerStatsButtonState);
playerStatsDialog.addEventListener("click", handleDialogBackdropClick);
importPdfButton.addEventListener("click", () => importProfixioPdf("replace"));
langEnButton.addEventListener("click", () => setLanguage("en-US"));
langSvButton.addEventListener("click", () => setLanguage("sv-SE"));

render();

function render() {
  renderChromeText();
  renderActions();
  normalizeFlowState({ advanceCompleted: false });
  renderFlow();
  renderMetrics();
  renderSettingsButtonState();
  renderImportButtonState();
  renderPlayerStatsButtonState();
  renderSettings();
  renderImportStatus();
  renderPlayerStatsTable();
  renderPlayLog();
  renderEventLog();
  playCount.textContent = String(state.plays.length);
  eventCount.textContent = String(state.events.length);
  syncMobileFlowViewport();
}

function renderChromeText() {
  document.documentElement.lang = state.language === "sv-SE" ? "sv" : "en";
  document.title = t("appTitle");
  document.querySelector("#hero-eyebrow").textContent = t("heroEyebrow");
  document.querySelector("#hero-title").textContent = t("heroTitle");
  document.querySelector("#hero-copy").textContent = t("heroCopy");
  document.querySelector("#play-count-label").textContent = t("playCountLabel");
  document.querySelector("#event-count-label").textContent = t("eventCountLabel");
  document.querySelector("#entry-pad-title").textContent = t("entryPadTitle");
  document.querySelector("#reset-flow").textContent = t("resetFlow");
  document.querySelector("#start-action-title").textContent = t("startActionTitle");
  document.querySelector("#start-action-copy").textContent = t("startActionCopy");
  document.querySelector("#live-state-title").textContent = t("liveStateTitle");
  document.querySelector("#seed-demo").textContent = t("addDemoSequence");
  document.querySelector("#recorded-plays-title").textContent = t("recordedPlaysTitle");
  document.querySelector("#derived-events-title").textContent = t("derivedEventsTitle");
  document.querySelector("#derived-events-pill").textContent = t("autoGenerated");
  document.querySelector("#settings-title").textContent = t("settingsTitle");
  document.querySelector("#settings-copy").textContent = t("settingsCopy");
  document.querySelector("#toggle-settings").setAttribute("aria-label", t("openSettings"));
  document.querySelector("#close-settings").setAttribute("aria-label", t("closeSettings"));
  document.querySelector("#toggle-import").textContent = t("importPdfButton");
  document.querySelector("#toggle-import").setAttribute("aria-label", t("openImport"));
  document.querySelector("#toggle-player-stats").textContent = t("playerStatsTitle");
  document.querySelector("#toggle-player-stats").setAttribute("aria-label", t("openPlayerStats"));
  document.querySelector("#import-title").textContent = t("importTitle");
  document.querySelector("#import-copy").textContent = t("importCopy");
  document.querySelector("#close-import").setAttribute("aria-label", t("closeImport"));
  document.querySelector("#player-stats-title").textContent = t("playerStatsTitle");
  document.querySelector("#player-stats-copy").textContent = t("playerStatsCopy");
  document.querySelector("#close-player-stats").setAttribute("aria-label", t("closePlayerStats"));
  document.querySelector("#import-file-label").textContent = t("importPdfLabel");
  document.querySelector("#import-file-note").textContent = t("importPdfNote");
  document.querySelector("#import-team-label").textContent = t("importTeamLabel");
  importTeamSide.options[0].textContent = t("importTeamHome");
  importTeamSide.options[1].textContent = t("importTeamAway");
  importPdfButton.textContent = t("importPdfButton");
  backStepButton.textContent = t("back");
  nextStepButton.textContent = t("next");
  langEnButton.classList.toggle("is-active", state.language === "en-US");
  langSvButton.classList.toggle("is-active", state.language === "sv-SE");
}

function renderActions() {
  actionGrid.innerHTML = "";

  actionDefinitions.forEach((action) => {
    const button = document.createElement("button");
    button.type = "button";
    button.className = [
      "select-button",
      state.selectedActionId === action.id ? "is-selected" : "",
    ].join(" ").trim();
    button.innerHTML = `
      ${renderActionButtonContent(action.id)}
      <small>${getActionDescription(action.id)}</small>
    `;
    button.addEventListener("click", () => {
      const isSameAction = state.selectedActionId === action.id;
      state.selectedActionId = action.id;
      state.context = isSameAction ? state.context : {};
      state.currentStageIndex = 0;
      pruneConditionalContext();
      render();
    });
    actionGrid.appendChild(button);
  });
}

function renderFlow() {
  renderSummary();
  const stages = getFlowStages();

  if (!state.selectedActionId) {
    flowTitle.textContent = t("guidedFlow");
    flowCopy.textContent = t("guidedFlowCopy");
    flowProgress.innerHTML = "";
    flowStageLabel.textContent = t("waitingForAction");
    stageHost.className = "stage-host empty-state";
    stageHost.textContent = t("selectPrimaryAction");
    backStepButton.disabled = true;
    nextStepButton.disabled = true;
    commitButton.disabled = true;
    commitButton.textContent = state.editingPlayId ? t("saveChanges") : t("recordPlay");
    return;
  }

  const activeIndex = Math.min(state.currentStageIndex, Math.max(0, stages.length - 1));
  state.currentStageIndex = activeIndex;
  const activeStage = stages[activeIndex];

  flowTitle.textContent = `${getActionLabel(state.selectedActionId)} ${t("flowSuffix")}`;
  flowCopy.textContent = activeStage.description;
  flowStageLabel.textContent = t("stepOf", { current: activeIndex + 1, total: stages.length });
  flowProgress.innerHTML = stages
    .map((stage, index) => {
      const classes = [
        "progress-pill",
        index === activeIndex ? "is-active" : "",
        isStageComplete(stage) ? "is-complete" : "",
      ].filter(Boolean).join(" ");
      return `<span class="${classes}">${stage.shortLabel}</span>`;
    })
    .join("");

  stageHost.className = "stage-host";
  stageHost.innerHTML = "";
  renderStage(activeStage);

  backStepButton.disabled = activeIndex === 0;
  nextStepButton.disabled = activeIndex >= stages.length - 1 || !isStageComplete(activeStage);
  commitButton.disabled = !isFlowComplete();
  commitButton.textContent = state.editingPlayId ? t("saveChanges") : t("recordPlay");
}

function handleFlowInputChange(changedStageIndex = state.currentStageIndex) {
  pruneConditionalContext();

  const stages = getFlowStages();
  if (!stages.length) {
    render();
    return;
  }

  const lastIndex = Math.max(0, stages.length - 1);
  if (changedStageIndex < lastIndex) {
    state.currentStageIndex = Math.min(changedStageIndex + 1, lastIndex);
    render();
    return;
  }

  normalizeFlowState({ advanceCompleted: true });

  if (state.autoRecordLastDetail && isFlowComplete()) {
    commitPlay();
    return;
  }

  render();
}

function syncMobileFlowViewport() {
  if (!isMobileViewport()) {
    lastFlowViewportKey = "";
    return;
  }

  const viewportKey = state.selectedActionId
    ? `${state.selectedActionId}:${state.currentStageIndex}:${state.selectedPlayerId ?? "none"}:${state.context.outcome ?? "none"}`
    : "idle";

  if (viewportKey === lastFlowViewportKey) {
    return;
  }

  lastFlowViewportKey = viewportKey;

  const target = state.selectedActionId ? flowCard : actionStepCard;
  window.requestAnimationFrame(() => {
    target.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  });
}

function renderStage(stage) {
  const wrapper = document.createElement("div");
  wrapper.className = "context-group stage-group";

  const label = document.createElement("p");
  label.className = "context-group-label";
  label.textContent = stage.label;
  wrapper.appendChild(label);

  const caption = document.createElement("p");
  caption.className = "stage-copy";
  caption.textContent = stage.description;
  wrapper.appendChild(caption);

  const options = document.createElement("div");
  options.className = stage.type === "player" ? "player-grid" : "context-options";

  if (stage.type === "player") {
    players.forEach((player) => {
      const button = document.createElement("button");
      button.type = "button";
      button.className = `select-button ${state.selectedPlayerId === player.id ? "is-selected" : ""}`.trim();
      button.innerHTML = `#${player.number}<small>${player.name}</small>`;
      button.addEventListener("click", () => {
        state.selectedPlayerId = player.id;
        handleFlowInputChange(state.currentStageIndex);
      });
      options.appendChild(button);
    });
  } else {
    stage.options.forEach((option) => {
      const button = document.createElement("button");
      button.type = "button";
      const isSelected = state.context[stage.key] === option;
      button.className = `select-button ${isSelected ? "is-selected" : ""}`.trim();
      button.textContent = formatContextOption(stage.key, option);
      button.addEventListener("click", () => {
        state.context[stage.key] = option;
        if (stage.key === "outcome" && option !== "GOAL") {
          delete state.context.assistPlayerId;
        }
        handleFlowInputChange(state.currentStageIndex);
      });
      options.appendChild(button);
    });
  }

  wrapper.appendChild(options);
  stageHost.appendChild(wrapper);
}

function renderSummary() {
  const player = getSelectedPlayer();
  const action = state.selectedActionId ? getActionLabel(state.selectedActionId) : "None";
  const parts = [
    `${t("summaryMode")}: ${state.editingPlayId ? t("modeEditing") : t("modeCreating")}`,
    `${t("summaryPlayer")}: ${player ? `#${player.number} ${player.name}` : t("notSelected")}`,
    `${t("summaryAction")}: ${action ?? t("notSelected")}`,
  ];

  const contextEntries = Object.entries(state.context);
  if (contextEntries.length) {
    contextEntries.forEach(([key, value]) => {
      parts.push(`${getContextLabel(key).toUpperCase()}: ${formatContextOption(key, value)}`);
    });
  } else {
    parts.push(`${t("summaryContext")}: ${t("noContextSelected")}`);
  }

  selectionSummary.innerHTML = parts.join("<br>");
}

function renderMetrics() {
  const summary = calculateSummary(state.events);
  const groups = [
    {
      title: t("metricGroupShooting"),
      cards: [
        { label: t("metricTotalShots"), value: summary.totalShots, caption: t("metricTotalShotsCaption") },
        { label: t("metricGoals"), value: summary.goals, caption: t("metricGoalsCaption") },
        { label: t("metricMisses"), value: summary.misses, caption: t("metricMissesCaption") },
        { label: t("metricShotEfficiency"), value: `${summary.shotEfficiency}%`, caption: t("metricShotEfficiencyCaption") },
      ],
    },
    {
      title: t("metricGroupGoalkeeping"),
      cards: [
        { label: t("metricShotsOnGoal"), value: summary.shotsOnGoal, caption: t("metricShotsOnGoalCaption") },
        { label: t("metricSaves"), value: summary.saves, caption: t("metricSavesCaption") },
        { label: t("metricSavePercentage"), value: `${summary.savePercentage}%`, caption: t("metricSavePercentageCaption") },
      ],
    },
    {
      title: t("metricGroupPenalties"),
      cards: [
        { label: t("metricPenalties"), value: summary.penalties, caption: t("metricPenaltiesCaption") },
        { label: t("metricPenaltyGoals"), value: summary.penaltyGoals, caption: t("metricPenaltyGoalsCaption") },
        { label: t("metricPenaltyMisses"), value: summary.penaltyMisses, caption: t("metricPenaltyMissesCaption") },
        { label: t("metricPenaltyEfficiency"), value: `${summary.penaltyEfficiency}%`, caption: t("metricPenaltyEfficiencyCaption") },
      ],
    },
    {
      title: t("metricGroupDiscipline"),
      cards: [
        { label: t("metricTechFaults"), value: summary.techFaults, caption: t("metricTechFaultsCaption") },
        { label: t("metricSuspensions"), value: summary.suspensions, caption: t("metricSuspensionsCaption") },
        { label: t("metricWarnings"), value: summary.warnings, caption: t("metricWarningsCaption") },
      ],
    },
  ];

  metricsGrid.innerHTML = "";
  groups.forEach((group) => {
    const section = document.createElement("section");
    section.className = "metric-group";
    section.innerHTML = `<h3 class="metric-group-title">${group.title}</h3>`;

    const cardGrid = document.createElement("div");
    cardGrid.className = "metric-group-grid";

    group.cards.forEach((card) => {
      const node = document.createElement("article");
      node.className = "metric-card";
      node.innerHTML = `
        <span class="stat-label">${card.label}</span>
        <strong class="metric-value">${card.value}</strong>
        <p class="metric-caption">${card.caption}</p>
      `;
      cardGrid.appendChild(node);
    });

    section.appendChild(cardGrid);
    metricsGrid.appendChild(section);
  });
}

function getPlayerStatsColumns() {
  return [
    { key: "player", label: t("playerStatsPlayer") },
    { key: "shots", label: t("playerStatsShots") },
    { key: "goals", label: t("playerStatsGoals") },
    { key: "misses", label: t("playerStatsMisses") },
    { key: "efficiency", label: t("playerStatsEfficiency"), format: (value) => `${value}%` },
    { key: "shotsOnGoal", label: t("playerStatsShotsOnGoal") },
    { key: "saves", label: t("playerStatsSaves") },
    { key: "savePercentage", label: t("playerStatsSavePercentage"), format: (value) => `${value}%` },
    { key: "penalties", label: t("playerStatsPenalties") },
    { key: "penaltyGoals", label: t("playerStatsPenaltyGoals") },
    { key: "penaltyMisses", label: t("playerStatsPenaltyMisses") },
    { key: "penaltyEfficiency", label: t("playerStatsPenaltyEfficiency"), format: (value) => `${value}%` },
    { key: "techFaults", label: t("playerStatsTechFaults") },
    { key: "suspensions", label: t("playerStatsSuspensions") },
    { key: "warnings", label: t("playerStatsWarnings") },
  ];
}

function buildPlayerStatsRows(events) {
  const rowsByPlayer = new Map();
  const playerNameById = new Map(players.map((player) => [player.id, `#${player.number} ${player.name}`]));

  events.forEach((event) => {
    const label = playerNameById.get(event.playerId)
      ?? findPlayerLabelForEvent(event)
      ?? event.playerLabel;
    if (!label || label === "Goalkeeper") {
      return;
    }

    const row = rowsByPlayer.get(label) ?? {
      player: label,
      shots: 0,
      goals: 0,
      misses: 0,
      efficiency: 0,
      shotsOnGoal: 0,
      saves: 0,
      savePercentage: 0,
      penalties: 0,
      penaltyGoals: 0,
      penaltyMisses: 0,
      penaltyEfficiency: 0,
      techFaults: 0,
      suspensions: 0,
      warnings: 0,
    };

    if (event.statType === "SHOT") {
      row.shots += 1;
    }
    if (event.statType === "GOAL") {
      row.goals += 1;
      if (event.dimensions.attack_type === "penalty") {
        row.penaltyGoals += 1;
      }
    }
    if (event.statType === "SHOT_OFF") {
      row.misses += 1;
      if (event.dimensions.attack_type === "penalty") {
        row.penaltyMisses += 1;
      }
    }
    if (event.statType === "SHOT_ON_GOAL") {
      row.shotsOnGoal += 1;
    }
    if (event.statType === "SAVE") {
      row.saves += 1;
    }
    if (event.statType === "PENALTY_SHOT") {
      row.penalties += 1;
    }
    if (event.statType === "TECH_FAULT") {
      row.techFaults += 1;
    }
    if (event.statType === "SUSPENSION_2") {
      row.suspensions += 1;
    }
    if (event.statType === "WARNING") {
      row.warnings += 1;
    }

    rowsByPlayer.set(label, row);
  });

  return [...rowsByPlayer.values()]
    .map((row) => ({
      ...row,
      efficiency: row.shots ? Math.round((row.goals / row.shots) * 100) : 0,
      savePercentage: row.shotsOnGoal ? Math.round((row.saves / row.shotsOnGoal) * 100) : 0,
      penaltyEfficiency: row.penalties ? Math.round((row.penaltyGoals / row.penalties) * 100) : 0,
    }));
}

function findPlayerLabelForEvent(event) {
  const player = players.find((entry) => entry.id === event.playerId);
  if (player) {
    return `#${player.number} ${player.name}`;
  }

  const byName = players.find((entry) => entry.name === event.playerLabel);
  return byName ? `#${byName.number} ${byName.name}` : event.playerLabel;
}

function sortPlayerStatsRows(rows, sort) {
  const direction = sort.direction === "asc" ? 1 : -1;
  return rows.slice().sort((left, right) => {
    const leftValue = left[sort.key];
    const rightValue = right[sort.key];

    if (typeof leftValue === "number" && typeof rightValue === "number" && leftValue !== rightValue) {
      return (leftValue - rightValue) * direction;
    }

    const textCompare = String(leftValue).localeCompare(String(rightValue), "sv", { numeric: true, sensitivity: "base" });
    if (textCompare !== 0) {
      return textCompare * direction;
    }

    return left.player.localeCompare(right.player, "sv", { numeric: true, sensitivity: "base" });
  });
}

function togglePlayerStatsSort(key) {
  state.playerStatsSort = state.playerStatsSort.key === key
    ? { key, direction: state.playerStatsSort.direction === "asc" ? "desc" : "asc" }
    : { key, direction: key === "player" ? "asc" : "desc" };
  renderPlayerStatsTable();
}

function renderSettings() {
  settingsPanel.innerHTML = "";

  if (!Object.keys(contextSettings).length) {
    settingsPanel.className = "settings-panel empty-state";
    settingsPanel.textContent = t("noConfigurableContext");
    return;
  }

  settingsPanel.className = "settings-panel";

  const presetsCard = document.createElement("article");
  presetsCard.className = "settings-card";
  presetsCard.innerHTML = `
    <div class="settings-card-header">
      <div>
        <p class="log-item-title">${t("presetsTitle")}</p>
        <p class="log-item-subtitle">${t("presetsCopy")}</p>
      </div>
    </div>
  `;

  const presetRow = document.createElement("div");
  presetRow.className = "settings-toggle-list";

  const detailedButton = document.createElement("button");
  detailedButton.type = "button";
  detailedButton.className = "settings-toggle is-enabled";
  detailedButton.innerHTML = `<span>${t("presetDetailed")}</span>`;
  detailedButton.addEventListener("click", () => {
    applySettingsPreset("detailed");
  });
  presetRow.appendChild(detailedButton);

  const simpleButton = document.createElement("button");
  simpleButton.type = "button";
  simpleButton.className = "settings-toggle is-enabled";
  simpleButton.innerHTML = `<span>${t("presetSimple")}</span>`;
  simpleButton.addEventListener("click", () => {
    applySettingsPreset("simple");
  });
  presetRow.appendChild(simpleButton);

  presetsCard.appendChild(presetRow);
  settingsPanel.appendChild(presetsCard);

  const displayCard = document.createElement("article");
  displayCard.className = "settings-card";
  displayCard.innerHTML = `
    <div class="settings-card-header">
      <div>
        <p class="log-item-title">${t("displaySettingsTitle")}</p>
        <p class="log-item-subtitle">${t("displaySettingsCopy")}</p>
      </div>
    </div>
  `;

  const displayToggleRow = document.createElement("div");
  displayToggleRow.className = "settings-toggle-list";
  const iconToggle = document.createElement("button");
  iconToggle.type = "button";
  iconToggle.className = `settings-toggle ${state.showActionIcons ? "is-enabled" : "is-disabled"}`.trim();
  iconToggle.innerHTML = `
    <span>${t("showActionIcons")}</span>
    <strong>${state.showActionIcons ? t("toggleOn") : t("toggleOff")}</strong>
  `;
  iconToggle.addEventListener("click", () => {
    state.showActionIcons = !state.showActionIcons;
    render();
  });
  displayToggleRow.appendChild(iconToggle);

  const autoRecordToggle = document.createElement("button");
  autoRecordToggle.type = "button";
  autoRecordToggle.className = `settings-toggle ${state.autoRecordLastDetail ? "is-enabled" : "is-disabled"}`.trim();
  autoRecordToggle.innerHTML = `
    <span>${t("autoRecordLastDetail")}</span>
    <strong>${state.autoRecordLastDetail ? t("toggleOn") : t("toggleOff")}</strong>
  `;
  autoRecordToggle.addEventListener("click", () => {
    state.autoRecordLastDetail = !state.autoRecordLastDetail;
    render();
  });
  displayToggleRow.appendChild(autoRecordToggle);

  displayCard.appendChild(displayToggleRow);
  settingsPanel.appendChild(displayCard);

  Object.keys(contextSettings).forEach((actionId) => {
    const groups = Object.keys(state.contextSettings[actionId]).map((key) => ({ key, label: getContextLabel(key) }));
    const card = document.createElement("article");
    card.className = "settings-card";

    const heading = document.createElement("div");
    heading.className = "settings-card-header";
    heading.innerHTML = `
      <div>
        <p class="log-item-title">${getActionLabel(actionId)}</p>
        <p class="log-item-subtitle">${t("settingsGroupCopy")}</p>
      </div>
    `;
    card.appendChild(heading);

    const toggleRow = document.createElement("div");
    toggleRow.className = "settings-toggle-list";

    groups.forEach((group) => {
      const button = document.createElement("button");
      button.type = "button";
      const isEnabled = isContextEnabled(actionId, group.key);
      button.className = `settings-toggle ${isEnabled ? "is-enabled" : "is-disabled"}`.trim();
      button.innerHTML = `
        <span>${group.label}</span>
        <strong>${isEnabled ? t("toggleOn") : t("toggleOff")}</strong>
      `;
      button.addEventListener("click", () => {
        toggleContextSetting(actionId, group.key);
      });
      toggleRow.appendChild(button);
    });

    card.appendChild(toggleRow);
    settingsPanel.appendChild(card);
  });
}

function renderSettingsButtonState() {
  const isOpen = settingsDialog.open;
  toggleSettingsButton.setAttribute("aria-expanded", String(isOpen));
  toggleSettingsButton.classList.toggle("is-active", isOpen);
}

function renderImportButtonState() {
  const isOpen = importDialog.open;
  toggleImportButton.setAttribute("aria-expanded", String(isOpen));
  toggleImportButton.classList.toggle("is-active", isOpen);
}

function renderPlayerStatsButtonState() {
  const isOpen = playerStatsDialog.open;
  togglePlayerStatsButton.setAttribute("aria-expanded", String(isOpen));
  togglePlayerStatsButton.classList.toggle("is-active", isOpen);
}

function renderImportStatus() {
  if (!state.importStatus) {
    importStatus.className = "import-status empty-state";
    importStatus.textContent = t("importEmpty");
    return;
  }

  importStatus.className = "import-status context-group";
  importStatus.textContent = state.importStatus;
}

function renderPlayerStatsTable() {
  const rows = buildPlayerStatsRows(state.events);
  if (!rows.length) {
    playerStatsTableHost.className = "player-stats-table-host empty-state";
    playerStatsTableHost.textContent = t("playerStatsEmpty");
    return;
  }

  const columns = getPlayerStatsColumns();
  const sortedRows = sortPlayerStatsRows(rows, state.playerStatsSort);
  playerStatsTableHost.className = "player-stats-table-host";
  playerStatsTableHost.innerHTML = "";

  const table = document.createElement("table");
  table.className = "player-stats-table";

  const thead = document.createElement("thead");
  const headRow = document.createElement("tr");
  columns.forEach((column) => {
    const th = document.createElement("th");
    const button = document.createElement("button");
    button.type = "button";
    button.className = `table-sort ${state.playerStatsSort.key === column.key ? "is-active" : ""}`.trim();
    const direction = state.playerStatsSort.key === column.key && state.playerStatsSort.direction === "asc" ? "asc" : "desc";
    const indicator = state.playerStatsSort.key === column.key ? (state.playerStatsSort.direction === "asc" ? " ↑" : " ↓") : "";
    button.textContent = `${column.label}${indicator}`;
    button.setAttribute("aria-sort", state.playerStatsSort.key === column.key ? direction : "none");
    button.addEventListener("click", () => {
      togglePlayerStatsSort(column.key);
    });
    th.appendChild(button);
    headRow.appendChild(th);
  });
  thead.appendChild(headRow);

  const tbody = document.createElement("tbody");
  sortedRows.forEach((row) => {
    const tr = document.createElement("tr");
    columns.forEach((column) => {
      const td = document.createElement("td");
      td.textContent = String(column.format ? column.format(row[column.key]) : row[column.key]);
      tr.appendChild(td);
    });
    tbody.appendChild(tr);
  });

  table.appendChild(thead);
  table.appendChild(tbody);
  playerStatsTableHost.appendChild(table);
}

function renderPlayLog() {
  if (!state.plays.length) {
    playLog.className = "log-list empty-state";
    playLog.textContent = t("playLogEmpty");
    lastPlayLabel.textContent = t("noPlaysYet");
    return;
  }

  playLog.className = "log-list";
  playLog.innerHTML = "";
  const latestPlay = state.plays[state.plays.length - 1];
  lastPlayLabel.textContent = latestPlay.timeLabel;

  state.plays.slice().reverse().forEach((play) => {
    const item = document.createElement("article");
    item.className = "log-item";
    const isEditing = state.editingPlayId === play.id;
    const canEdit = play.editable !== false;
    item.innerHTML = `
      <p class="log-item-title">${formatPlayLabel(play.actionId, buildPlayTitle(play))}</p>
      <p class="log-item-subtitle">${play.timeLabel} • ${buildPlaySource(play)}</p>
      <div class="token-row">${play.contextTokens.map((token) => `<span class="token">${token}</span>`).join("")}</div>
      <div class="action-row">
        ${canEdit ? `<button class="ghost-button log-action" type="button" data-action="edit">${isEditing ? t("editing") : t("edit")}</button>` : ""}
        <button class="ghost-button log-action log-action-danger" type="button" data-action="delete">${t("delete")}</button>
      </div>
    `;

    item.querySelector('[data-action="edit"]')?.addEventListener("click", () => {
      loadPlayIntoEditor(play.id);
    });
    item.querySelector('[data-action="delete"]').addEventListener("click", () => {
      deletePlay(play.id);
    });
    playLog.appendChild(item);
  });
}

function renderEventLog() {
  if (!state.events.length) {
    eventLog.className = "log-list empty-state";
    eventLog.textContent = t("eventLogEmpty");
    return;
  }

  eventLog.className = "log-list";
  eventLog.innerHTML = "";

  state.events.slice().reverse().forEach((event) => {
    const item = document.createElement("article");
    item.className = "log-item";
    const dimensions = Object.entries(event.dimensions)
      .map(([key, value]) => `${key}=${formatDimensionValue(key, value)}`);

    item.innerHTML = `
      <p class="log-item-title">${event.statType}</p>
      <p class="log-item-subtitle">${event.playerLabel} • ${event.timeLabel}</p>
      <div class="token-row">${dimensions.map((token) => `<span class="token">${token}</span>`).join("")}</div>
    `;
    eventLog.appendChild(item);
  });
}

function commitPlay() {
  if (!isFlowComplete()) {
    return;
  }

  const player = getSelectedPlayer();
  const actionId = state.selectedActionId;
  const existingPlay = state.editingPlayId
    ? state.plays.find((play) => play.id === state.editingPlayId) ?? null
    : null;
  const preserveImportedMetadata = Boolean(existingPlay?.imported && existingPlay.actionId === actionId);
  const playId = existingPlay?.id ?? crypto.randomUUID();
  const timestamp = existingPlay ? new Date(existingPlay.time) : new Date();
  const derivedEvents = deriveEvents({
    playId,
    player,
    actionId,
    context: { ...state.context },
    timestamp,
  });

  const play = {
    id: playId,
    gameId: existingPlay?.gameId ?? "demo-game",
    time: timestamp.toISOString(),
    timeLabel: existingPlay?.timeLabel ?? formatTime(timestamp),
    playerId: player.id,
    actionId,
    context: { ...state.context },
    sourceText: preserveImportedMetadata ? existingPlay.sourceText : `${player.name} -> ${actionId}`,
    label: preserveImportedMetadata ? existingPlay.label : `${player.name} ${actionId.replace("_", " ")}`,
    contextTokens: buildPlayContextTokens({ existingPlay, context: state.context, preserveImportedMetadata }),
    imported: preserveImportedMetadata,
  };

  if (existingPlay) {
    const playIndex = state.plays.findIndex((entry) => entry.id === existingPlay.id);
    state.plays[playIndex] = play;
    state.events = state.events.filter((event) => event.playId !== existingPlay.id);
    state.events.push(...derivedEvents);
  } else {
    state.plays.push(play);
    state.events.push(...derivedEvents);
  }

  resetFlow();
  render();
}

function resetFlow() {
  state.selectedPlayerId = null;
  state.selectedActionId = null;
  state.context = {};
  state.editingPlayId = null;
  state.currentStageIndex = 0;
  render();
}

function getContextGroups(actionId) {
  if (!actionId) {
    return [];
  }

  const groups = (contextDefinitions[actionId] ?? []).filter((group) => isContextEnabled(actionId, group.key));

  if (actionId === "SHOT" && state.context.outcome === "GOAL" && isContextEnabled(actionId, "assistPlayerId")) {
    groups.push({
      key: "assistPlayerId",
      label: getContextLabel("assistPlayerId"),
      options: ["NONE", ...players.filter((player) => player.id !== state.selectedPlayerId).map((player) => player.id)],
    });
  }

  return groups;
}

function getFlowStages(actionId = state.selectedActionId) {
  if (!actionId) {
    return [];
  }

  return [
    {
      type: "player",
      key: "player",
      label: t("choosePlayer"),
      shortLabel: t("choosePlayer"),
      description: t("choosePlayerCopy"),
    },
    ...getContextGroups(actionId).map((group) => ({
      type: "context",
      key: group.key,
      label: getContextLabel(group.key),
      shortLabel: getContextLabel(group.key),
      description: t("captureContext", { label: getContextLabel(group.key).toLowerCase() }),
      options: group.options,
    })),
  ];
}

function getCurrentStage() {
  const stages = getFlowStages();
  if (!stages.length) {
    return null;
  }

  return stages[Math.min(state.currentStageIndex, stages.length - 1)];
}

function normalizeFlowState({ advanceCompleted = false } = {}) {
  if (!state.selectedActionId) {
    return;
  }

  pruneConditionalContext();

  const stages = getFlowStages();
  if (!stages.length) {
    state.currentStageIndex = 0;
    return;
  }

  state.currentStageIndex = Math.min(state.currentStageIndex, stages.length - 1);

  if (!advanceCompleted) {
    return;
  }

  for (let index = state.currentStageIndex; index < stages.length; index += 1) {
    const stage = stages[index];

    if (stage.type === "player") {
      if (!state.selectedPlayerId) {
        state.currentStageIndex = index;
        return;
      }
      continue;
    }

    if (state.context[stage.key]) {
      continue;
    }

    if (stage.options.length !== 1) {
      state.currentStageIndex = index;
      return;
    }

    state.context[stage.key] = stage.options[0];
  }

  state.currentStageIndex = stages.length - 1;
}

function pruneConditionalContext() {
  if (state.selectedActionId !== "SHOT" || state.context.outcome !== "GOAL") {
    delete state.context.assistPlayerId;
  }
}

function isContextEnabled(actionId, key) {
  return Boolean(state.contextSettings[actionId]?.[key]);
}

function toggleContextSetting(actionId, key) {
  const nextValue = !state.contextSettings[actionId][key];
  state.contextSettings[actionId][key] = nextValue;

  if (!nextValue) {
    delete state.context[key];
  }

  if (state.selectedActionId === actionId) {
    const stages = getFlowStages(actionId);
    state.currentStageIndex = Math.min(state.currentStageIndex, Math.max(0, stages.length - 1));
  }

  render();
}

function applySettingsPreset(presetName) {
  const preset = settingsPresets[presetName];
  if (!preset) {
    return;
  }

  Object.entries(preset).forEach(([actionId, config]) => {
    if (!state.contextSettings[actionId]) {
      return;
    }

    Object.entries(config).forEach(([key, value]) => {
      if (key in state.contextSettings[actionId]) {
        state.contextSettings[actionId][key] = value;
      }
    });
  });

  if (state.selectedActionId) {
    const allowedKeys = new Set(getContextGroups(state.selectedActionId).map((group) => group.key));
    Object.keys(state.context).forEach((key) => {
      if (!allowedKeys.has(key) && key !== "outcome") {
        delete state.context[key];
      }
    });
  }

  pruneConditionalContext();
  normalizeFlowState({ advanceCompleted: true });
  render();
}

function openSettingsDialog() {
  if (!settingsDialog.open) {
    settingsDialog.showModal();
  }
  renderSettingsButtonState();
}

function closeSettingsDialog() {
  if (settingsDialog.open) {
    settingsDialog.close();
  }
  renderSettingsButtonState();
}

function openImportDialog() {
  if (!importDialog.open) {
    importDialog.showModal();
  }
  renderImportButtonState();
}

function closeImportDialog() {
  if (importDialog.open) {
    importDialog.close();
  }
  renderImportButtonState();
}

function openPlayerStatsDialog() {
  if (!playerStatsDialog.open) {
    playerStatsDialog.showModal();
  }
  renderPlayerStatsButtonState();
}

function closePlayerStatsDialog() {
  if (playerStatsDialog.open) {
    playerStatsDialog.close();
  }
  renderPlayerStatsButtonState();
}

function handleDialogBackdropClick(event) {
  const dialog = event.currentTarget;
  const bounds = dialog.getBoundingClientRect();
  const clickedInside =
    event.clientX >= bounds.left &&
    event.clientX <= bounds.right &&
    event.clientY >= bounds.top &&
    event.clientY <= bounds.bottom;

  if (!clickedInside) {
    dialog.close();
  }
}

function isStageComplete(stage) {
  if (!stage) {
    return false;
  }

  if (stage.type === "player") {
    return Boolean(state.selectedPlayerId);
  }

  return Boolean(state.context[stage.key]);
}

function goToPreviousStage() {
  if (!state.selectedActionId) {
    return;
  }

  state.currentStageIndex = Math.max(0, state.currentStageIndex - 1);
  render();
}

function goToNextStage() {
  const currentStage = getCurrentStage();
  const stages = getFlowStages();
  if (!currentStage || !isStageComplete(currentStage)) {
    return;
  }

  state.currentStageIndex = Math.min(stages.length - 1, state.currentStageIndex + 1);
  render();
}

function renderActionButtonContent(actionId) {
  const icon = state.showActionIcons ? `<span class="action-icon">${getActionIcon(actionId)}</span>` : "";
  return `<span class="action-button-label">${icon}<span>${getActionLabel(actionId)}</span></span>`;
}

function formatPlayLabel(actionId, label) {
  return state.showActionIcons ? `${getActionIcon(actionId)} ${label}` : label;
}

function buildPlayTitle(play) {
  return `${play.playerLabel ?? playerLabelFromId(play.playerId)} ${getActionLabel(play.actionId)}`;
}

function buildPlaySource(play) {
  if (play.sourceText) {
    return play.sourceText;
  }

  return `${play.playerLabel ?? playerLabelFromId(play.playerId)} -> ${getActionLabel(play.actionId)}`;
}

function getActionIcon(actionId) {
  return actionIcons[actionId] ?? "•";
}

function getActionLabel(actionId) {
  return translations[state.language].action[actionId]?.label ?? actionId;
}

function getActionDescription(actionId) {
  return translations[state.language].action[actionId]?.description ?? actionId;
}

function getContextLabel(key) {
  return translations[state.language].contextLabel[key] ?? key;
}

function getSelectedPlayer() {
  return players.find((player) => player.id === state.selectedPlayerId) ?? null;
}

function isFlowComplete() {
  if (!state.selectedPlayerId || !state.selectedActionId) {
    return false;
  }

  const groups = getContextGroups(state.selectedActionId);
  return groups.every((group) => state.context[group.key]);
}

function deriveEvents({ playId, player, actionId, context, timestamp }) {
  const baseDimensions = buildBaseDimensions(context, actionId);
  const createEvent = (statType, playerLabel, dimensions = {}) => ({
    id: crypto.randomUUID(),
    playId,
    playerId: playerLabel,
    playerLabel,
    statType,
    dimensions: { ...dimensions },
    time: timestamp.toISOString(),
    timeLabel: formatTime(timestamp),
  });

  switch (actionId) {
    case "SHOT":
      return deriveShotEvents(player, baseDimensions, context, createEvent, "shot");
    case "PENALTY":
      return deriveShotEvents(player, baseDimensions, context, createEvent, "penalty");
    case "SAVE":
      return [
        createEvent("SAVE", player.name, baseDimensions),
        ...(context.height ? [createEvent(`SAVE_${context.height}`, player.name, baseDimensions)] : []),
      ];
    case "MISS":
      return [
        createEvent("SHOT_OFF", player.name, baseDimensions),
      ];
    case "TECH_FAULT":
      return [createEvent("TECH_FAULT", player.name)];
    case "STEAL":
      return [createEvent("STEAL", player.name)];
    case "BLOCK":
      return [createEvent("BLOCK", player.name)];
    case "CARD":
      return [
        createEvent(context.cardType === "YELLOW" ? "WARNING" : "CARD_RED", player.name, {
          card_type: context.cardType.toLowerCase(),
        }),
      ];
    case "SUSPENSION":
      return [
        createEvent("SUSPENSION_2", player.name, {
          duration: "2_min",
        }),
      ];
    default:
      return [createEvent(actionId, player.name)];
  }
}

function deriveShotEvents(player, baseDimensions, context, createEvent, shotType) {
  const events = [];
  const outcome = context.outcome;
  const shotDimensions = {
    ...baseDimensions,
    shot_type: shotType,
    ...(outcome ? { outcome: outcome.toLowerCase() } : {}),
  };

  if (outcome === "GOAL") {
    events.push(createEvent("GOAL", player.name, shotDimensions));
    events.push(createEvent("SHOT_ON_GOAL", player.name, baseDimensions));
    if (context.height) {
      events.push(createEvent(`GOAL_ALLOWED_${context.height}`, "Goalkeeper", shotDimensions));
    }
    if (shotType === "shot" && context.assistPlayerId && context.assistPlayerId !== "NONE") {
      events.push(createEvent("ASSIST", playerLabelFromId(context.assistPlayerId), {
        target_player: player.name,
        shot_type: shotType,
      }));
    }
  }

  if (outcome === "SAVE") {
    events.push(createEvent("SHOT_ON_GOAL", player.name, baseDimensions));
    if (context.height) {
      events.push(createEvent(`SAVE_${context.height}`, "Goalkeeper", shotDimensions));
    }
  }

  if (outcome === "MISS") {
    events.push(createEvent("SHOT_OFF", player.name, baseDimensions));
  }

  if (outcome === "BLOCK") {
    events.push(createEvent("SHOT_BLOCKED", player.name, baseDimensions));
  }

  if (shotType === "penalty") {
    events.push(createEvent("PENALTY_SHOT", player.name, shotDimensions));
  }

  events.push(createEvent("SHOT", player.name, shotDimensions));
  return events;
}

function buildBaseDimensions(context, actionId) {
  const dimensions = {};

  if (context.height) {
    dimensions.height = context.height.toLowerCase();
  }

  if (context.location) {
    dimensions.location = context.location.toLowerCase();
    if (context.location === "FAST_BREAK") {
      dimensions.attack_type = "fast_break";
    }
  }

  if (actionId === "PENALTY") {
    dimensions.location = "penalty";
    dimensions.attack_type = "penalty";
  }

  return dimensions;
}

function calculateSummary(events) {
  const totalShots = events.filter((event) => event.statType === "SHOT").length;
  const goals = events.filter((event) => event.statType === "GOAL").length;
  const misses = events.filter((event) => event.statType === "SHOT_OFF").length;
  const shotsOnGoal = events.filter((event) => event.statType === "SHOT_ON_GOAL").length;
  const saves = events.filter((event) => event.statType === "SAVE").length;
  const warnings = events.filter((event) => event.statType === "WARNING").length;
  const techFaults = events.filter((event) => event.statType === "TECH_FAULT").length;
  const suspensions = events.filter((event) => event.statType === "SUSPENSION_2").length;
  const penalties = events.filter((event) => event.statType === "PENALTY_SHOT").length;
  const penaltyGoals = events.filter(
    (event) => event.statType === "GOAL" && event.dimensions.attack_type === "penalty",
  ).length;
  const penaltyMisses = Math.max(0, penalties - penaltyGoals);

  return {
    totalShots,
    goals,
    misses,
    shotsOnGoal,
    saves,
    warnings,
    techFaults,
    suspensions,
    penalties,
    penaltyGoals,
    penaltyMisses,
    shotEfficiency: totalShots ? Math.round((goals / totalShots) * 100) : 0,
    savePercentage: shotsOnGoal ? Math.round((saves / shotsOnGoal) * 100) : 0,
    penaltyEfficiency: penalties ? Math.round((penaltyGoals / penalties) * 100) : 0,
  };
}

function seedDemoSequence() {
  const demoEntries = [
    { playerId: "p9", actionId: "SHOT", context: { height: "HIGH", location: "FAST_BREAK", outcome: "GOAL" } },
    { playerId: "p10", actionId: "SHOT", context: { height: "LOW", location: "BACKCOURT", outcome: "SAVE" } },
    { playerId: "p7", actionId: "PENALTY", context: { height: "LOW", outcome: "GOAL" } },
    { playerId: "p5", actionId: "BLOCK", context: {} },
    { playerId: "p8", actionId: "CARD", context: { cardType: "YELLOW" } },
  ];

  demoEntries.forEach((entry) => {
    const player = players.find((candidate) => candidate.id === entry.playerId);
    const playId = crypto.randomUUID();
    const timestamp = new Date();
    const derivedEvents = deriveEvents({
      playId,
      player,
      actionId: entry.actionId,
      context: entry.context,
      timestamp,
    });

    state.plays.push({
      id: playId,
      gameId: "demo-game",
      time: timestamp.toISOString(),
      timeLabel: formatTime(timestamp),
      playerId: player.id,
      actionId: entry.actionId,
      context: { ...entry.context },
      sourceText: `${player.name} -> ${entry.actionId}`,
      label: `${player.name} ${entry.actionId.replace("_", " ")}`,
      contextTokens: Object.entries(entry.context).map(([key, value]) => `${key}:${formatContextOption(key, value)}`),
    });

    state.events.push(...derivedEvents);
  });

  render();
}

async function importProfixioPdf(mode) {
  try {
    const file = importFile.files?.[0];
    if (!file) {
      throw new Error(t("importPdfNoFile"));
    }

    const payload = await parseProfixioTimelinePdf(file, importTeamSide.value);
    const imported = mapProfixioImportPayload(payload);

    if (mode === "replace") {
      state.plays = [];
      state.events = [];
      players = imported.players.length ? imported.players : [...defaultPlayers];
      resetFlow();
    } else if (imported.players.length) {
      players = imported.players;
    }

    const existingPlayIds = new Set(state.plays.map((play) => play.id));
    const existingEventIds = new Set(state.events.map((event) => event.id));

    imported.plays.forEach((play) => {
      if (!existingPlayIds.has(play.id)) {
        state.plays.push(play);
      }
    });

    imported.events.forEach((event) => {
      if (!existingEventIds.has(event.id)) {
        state.events.push(event);
      }
    });

    state.importStatus = t("importPdfSuccessDebug", {
      plays: imported.plays.length,
      events: imported.events.length,
      match: imported.matchLabel,
      debug: formatPdfDebug(payload.debug ?? {}),
    });
    closeImportDialog();
    render();
  } catch (error) {
    state.importStatus = t("importErrorPrefix", {
      message: error instanceof Error ? error.message : String(error),
    });
    render();
  }
}

function mapProfixioImportPayload(payload) {
  if (!payload || !Array.isArray(payload.timeline)) {
    throw new Error("Missing timeline array in imported JSON.");
  }

  const filteredTimeline = payload.timeline.filter((entry) => shouldImportTimelineEntry(entry));

  const matchId = payload.match?.matchId ?? "unknown";
  const gameId = `profixio-${matchId}`;
  const teamName = payload.teamName ?? "Imported team";
  const importedPlayers = buildImportedPlayers(payload.players ?? [], filteredTimeline, teamName);
  const matchLabel = [
    payload.match?.homeTeam,
    payload.match?.awayTeam,
  ].filter(Boolean).join(" vs ") || `match ${matchId}`;

  const plays = filteredTimeline.map((entry, index) => {
    const timestamp = normalizeImportedTimestamp(entry.createdAt, payload.match?.dateIso, index);
    const playId = `profixio-play-${matchId}-${entry.eventId ?? index}`;
    const playerKey = getImportedPlayerId(entry, teamName, index);
    const actionId = mapImportedActionToPlay(entry);
    const context = mapImportedContext(entry);

    return {
      id: playId,
      gameId,
      time: timestamp.toISOString(),
      timeLabel: entry.displayGameTime ?? formatTime(timestamp),
      playerId: playerKey,
      playerLabel: entry.playerName ?? entry.teamName ?? teamName,
      actionId,
      context,
      sourceText: buildImportedPlaySource(entry, payload.match, teamName, matchId),
      label: entry.description ?? entry.action ?? "Imported event",
      contextTokens: buildImportedPlayTokens(entry, context),
      imported: true,
    };
  });

  const events = filteredTimeline.flatMap((entry, index) => {
    const timestamp = normalizeImportedTimestamp(entry.createdAt, payload.match?.dateIso, index);
    const playId = `profixio-play-${matchId}-${entry.eventId ?? index}`;
    const playerId = getImportedPlayerId(entry, teamName, index);
    const actionId = mapImportedActionToPlay(entry);
    const context = mapImportedContext(entry);
    const player = {
      id: playerId,
      name: entry.playerName ?? entry.teamName ?? teamName,
    };
    const baseEvents = deriveEvents({
      playId,
      player,
      actionId,
      context,
      timestamp,
    }).map((event, derivedIndex) => ({
      ...event,
      id: `profixio-event-${matchId}-${entry.eventId ?? index}-${derivedIndex}`,
      playerId,
      playerLabel: event.playerLabel ?? player.name,
      dimensions: {
        ...event.dimensions,
        ...buildImportedEventDimensions(entry, payload.match),
      },
      timeLabel: entry.displayGameTime ?? event.timeLabel,
    }));

    const extraEvents = [];
    if (entry.assistPlayerName) {
      extraEvents.push({
        id: `profixio-event-${matchId}-${entry.eventId ?? index}-assist`,
        playId,
        playerId: getImportedAssistPlayerId(entry, index),
        playerLabel: entry.assistPlayerName,
        statType: "ASSIST",
        dimensions: {
          target_player: entry.playerName ?? "",
          match_number: payload.match?.matchNumber ?? "",
        },
        time: timestamp.toISOString(),
        timeLabel: entry.displayGameTime ?? formatTime(timestamp),
      });
    }

    return [...baseEvents, ...extraEvents];
  });

  return { plays, events, matchLabel, players: importedPlayers };
}

async function parseProfixioTimelinePdf(file, side) {
  if (typeof DecompressionStream === "undefined") {
    throw new Error(t("importPdfUnsupported"));
  }

  const buffer = await file.arrayBuffer();
  const pdfBytes = new Uint8Array(buffer);
  const pdfText = new TextDecoder("latin1").decode(buffer);
  const streams = extractPdfStreams(pdfBytes);
  const decompressed = [];
  const debug = {
    fileName: file.name,
    fileSize: file.size,
    streamCount: streams.length,
    decompressedCount: 0,
    matchedTextBlocks: 0,
    parsedTimelineRows: 0,
    mergedPreview: "",
    headerRows: "(none)",
  };

  for (const stream of streams) {
    try {
      const output = await readDecompressedDeflate(stream);
      const text = new TextDecoder("latin1").decode(output);
      decompressed.push(text);
      debug.decompressedCount += 1;
    } catch {
      // Ignore non-text streams.
    }
  }

  const mergedText = decompressed.join("\n");
  debug.mergedPreview = mergedText.slice(0, 1200).replace(/\s+/g, " ").trim() || "(empty)";
  const rows = decompressed.flatMap((content, pageIndex) => extractPdfTextRows(content, pageIndex));
  debug.matchedTextBlocks = rows.length;
  const parsedRows = buildPdfTimelineRows(rows);
  debug.parsedTimelineRows = parsedRows.length;
  const match = parsePdfMatchMetadata(rows, parsedRows, debug);
  const teamName = side === "away" ? match.awayTeam : match.homeTeam;
  const teamRows = parsedRows.filter((row) => matchesSelectedPdfSide(row.teamName, teamName));
  const filteredTimeline = collapsePdfPenaltyAwards(teamRows
    .map((row, index) => ({
      eventId: `pdf-${match.matchNumber}-${index}`,
      eventTypeId: null,
      action: inferPdfRowAction(row),
      description: row.actionText,
      teamId: side === "away" ? "away" : "home",
      teamName,
      playerId: row.playerNumber ? `pdf-${side}-${row.playerNumber}` : null,
      playerName: row.playerName || null,
      playerNumber: row.playerNumber || null,
      assistPlayerId: null,
      assistPlayerName: null,
      assistPlayerNumber: null,
      displayGameTime: row.time,
      period: null,
      timeInPeriod: row.time,
      score: parsePdfScore(row.score),
      goals: row.actionText.includes("Mål") ? 1 : null,
      comment: null,
      createdAt: null,
      sortOrder: buildPdfSortOrder(row.time, index),
    })));

  if (!filteredTimeline.length) {
    throw new Error(`${t("importPdfNoRows", { team: teamName })}\n\n${t("importPdfDebug", { debug: formatPdfDebug(debug) })}`);
  }

  return {
    teamName,
    players: extractPdfPlayers(teamRows, teamName, side),
    match: {
      matchId: match.matchNumber,
      matchNumber: match.matchNumber,
      homeTeam: match.homeTeam,
      awayTeam: match.awayTeam,
      dateIso: null,
    },
    timeline: filteredTimeline,
    debug,
  };
}

function mapImportedActionToPlay(entry) {
  const description = String(entry.description ?? "").toLowerCase();

  if (description.includes("7-m")) {
    return "PENALTY";
  }
  if (entry.action === "GOAL") {
    return "SHOT";
  }
  if (entry.action === "SAVE") {
    return "SAVE";
  }
  if (entry.action === "MISS") {
    return "MISS";
  }
  if (entry.action === "WARNING" || entry.action === "CARD") {
    return "CARD";
  }
  if (entry.action === "SUSPENSION") {
    return "SUSPENSION";
  }
  if (description.includes("kort")) {
    return "CARD";
  }
  if (description.includes("utvisning")) {
    return "SUSPENSION";
  }
  if (description.includes("block")) {
    return "BLOCK";
  }
  if (description.includes("stöld")) {
    return "STEAL";
  }
  return null;
}

function collapsePdfPenaltyAwards(entries) {
  const collapsed = [];

  for (let index = 0; index < entries.length; index += 1) {
    const current = entries[index];
    const description = String(current.description ?? "").toLowerCase().trim();
    const next = entries[index + 1];
    const nextDescription = String(next?.description ?? "").toLowerCase().trim();

    if (
      description === "tilldömd 7-m"
      && next
      && current.teamId === next.teamId
      && current.teamName === next.teamName
      && isPdfPenaltyResultDescription(nextDescription)
    ) {
      collapsed.push({
        ...next,
        eventId: current.eventId,
        action: inferPdfRowAction({ actionText: next.description }),
        description: next.description,
        sortOrder: next.sortOrder,
      });
      index += 1;
      continue;
    }

    collapsed.push(current);
  }

  return collapsed;
}

function isPdfPenaltyResultDescription(description) {
  return description === "mål 7-m" || description === "7-m miss" || description === "miss 7-m";
}

function isSupportedImportedAction(actionId) {
  return [
    "SHOT",
    "PENALTY",
    "SAVE",
    "MISS",
    "CARD",
    "SUSPENSION",
    "BLOCK",
    "STEAL",
  ].includes(actionId);
}

function extractPdfStreams(pdfBytes) {
  const streams = [];
  const streamMarker = new TextEncoder().encode("stream");
  const endstreamMarker = new TextEncoder().encode("endstream");

  let offset = 0;
  while (offset < pdfBytes.length) {
    const streamIndex = findByteSequence(pdfBytes, streamMarker, offset);
    if (streamIndex < 0) {
      break;
    }

    let dataStart = streamIndex + streamMarker.length;
    if (pdfBytes[dataStart] === 0x0d && pdfBytes[dataStart + 1] === 0x0a) {
      dataStart += 2;
    } else if (pdfBytes[dataStart] === 0x0a) {
      dataStart += 1;
    }

    const declaredLength = readPdfStreamLength(pdfBytes, streamIndex);
    const fallbackEndIndex = findByteSequence(pdfBytes, endstreamMarker, dataStart);
    const dataEnd = declaredLength && dataStart + declaredLength <= pdfBytes.length
      ? dataStart + declaredLength
      : fallbackEndIndex;

    if (dataEnd < 0) {
      break;
    }

    streams.push(pdfBytes.slice(dataStart, dataEnd));

    const nextOffset = declaredLength && dataStart + declaredLength <= pdfBytes.length
      ? findByteSequence(pdfBytes, endstreamMarker, dataEnd)
      : dataEnd;
    offset = nextOffset >= 0
      ? nextOffset + endstreamMarker.length
      : dataEnd + endstreamMarker.length;
  }

  return streams;
}

function readPdfStreamLength(pdfBytes, streamIndex) {
  const dictionaryStart = Math.max(0, streamIndex - 512);
  const dictionaryText = new TextDecoder("latin1").decode(pdfBytes.slice(dictionaryStart, streamIndex));
  const matches = [...dictionaryText.matchAll(/\/Length\s+(\d+)/g)];
  if (!matches.length) {
    return null;
  }

  return Number(matches[matches.length - 1][1]);
}

function findByteSequence(bytes, pattern, fromIndex = 0) {
  outer: for (let index = fromIndex; index <= bytes.length - pattern.length; index += 1) {
    for (let patternIndex = 0; patternIndex < pattern.length; patternIndex += 1) {
      if (bytes[index + patternIndex] !== pattern[patternIndex]) {
        continue outer;
      }
    }
    return index;
  }

  return -1;
}

async function readDecompressedDeflate(bytes) {
  const formats = ["deflate", "deflate-raw"];
  let lastError = null;

  for (const format of formats) {
    try {
      const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream(format));
      const buffer = await new Response(stream).arrayBuffer();
      return new Uint8Array(buffer);
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError ?? new Error("Unable to decompress PDF stream.");
}

function extractPdfTextRows(content, pageIndex = 0) {
  return [...content.matchAll(/BT\s+([0-9.]+)\s+([0-9.]+)\s+Td\s+\[\(([\s\S]*?)\)\]\s+TJ\s+ET/g)]
    .map((match) => ({
      x: Number(match[1]),
      y: Number(match[2]),
      page: pageIndex,
      text: decodePdfText(match[3]),
    }))
    .filter((row) => row.text);
}

function decodePdfText(value) {
  return value
    .replaceAll("\\(", "(")
    .replaceAll("\\)", ")")
    .replaceAll("\\n", " ")
    .replaceAll("\\\\", "\\")
    .replace(/\s+/g, " ")
    .trim();
}

function parsePdfMatchMetadata(rows, parsedRows = [], debug = null) {
  const headerLine = rows.find((row) => row.text.includes("Match nr:"));
  const titleCandidates = rows
    .filter((row) => row.y >= 620)
    .map((row) => row.text.replace(/\s+/g, " ").trim());

  if (debug) {
    debug.headerRows = titleCandidates.length ? titleCandidates.join("\n") : "(none)";
  }

  const matchNumber = headerLine?.text.match(/Match nr:\s*([^ ]+(?:\s+[^ ]+){0,4})/)?.[1]?.trim()
    ?? headerLine?.text.match(/Match nr:\s*(.+?)\s+Serie:/)?.[1]?.trim()
    ?? "unknown";

  let homeTeam = "";
  let awayTeam = "";

  const lastHeaderRow = [...titleCandidates].reverse().find((text) => splitPdfTeamNames(text));
  if (lastHeaderRow) {
    [homeTeam, awayTeam] = splitPdfTeamNames(lastHeaderRow);
  }

  const inferredTeams = inferPdfTeamsFromTimelineRows(parsedRows);
  if ((!homeTeam || !awayTeam) && inferredTeams) {
    [homeTeam, awayTeam] = inferredTeams;
  }

  if ((!homeTeam || !awayTeam) && headerLine) {
    const normalizedHeader = headerLine.text.replace(/\s+/g, " ").trim();
    const headerMatch = normalizedHeader.match(/Match nr:\s*(.*?)\s+Serie:\s*(.*?)\s+(.+?)\s+(.+)$/);

    if (headerMatch) {
      const tail = headerMatch[3] + " " + headerMatch[4];
      const teamSplit = splitPdfTeamNames(tail);
      if (teamSplit) {
        [homeTeam, awayTeam] = teamSplit;
      }
    }
  }

  if (!homeTeam || !awayTeam) {
    const fallbackCandidate = titleCandidates.find((text) => splitPdfTeamNames(text));
    if (fallbackCandidate) {
      [homeTeam, awayTeam] = splitPdfTeamNames(fallbackCandidate);
    }
  }

  if (!homeTeam || !awayTeam) {
    const candidateText = titleCandidates.length
      ? titleCandidates.join("\n")
      : unique(
        parsedRows
          .map((row) => row.teamName)
          .filter(Boolean),
      ).join("\n") || "(none)";
    const parsedRowText = parsedRows.length
      ? parsedRows
        .slice(0, 40)
        .map((row) => [
          row.time ?? "",
          row.score ?? "",
          row.teamName ?? "",
          row.actionText ?? "",
          row.playerNumber ?? "",
          row.playerName ?? "",
        ].join(" | "))
        .join("\n")
      : "(none)";
    throw new Error(
      `${t("importPdfTeamsNotFound")}\n\n${t("importPdfCandidates", { rows: candidateText })}\n\n${t("importPdfParsedRows", { rows: parsedRowText })}${debug ? `\n\n${t("importPdfDebug", { debug: formatPdfDebug(debug) })}` : ""}`,
    );
  }

  return { matchNumber, homeTeam, awayTeam };
}

function splitPdfTeamNames(text) {
  const normalized = String(text).replace(/\s+/g, " ").trim();
  if (!normalized) {
    return null;
  }

  if (/match nr:|serie:|datum:|arena:|rad$|^rad$|^tid$|^mål$|^lag$|^händelse$|^nr$|^spelare$/i.test(normalized)) {
    return null;
  }

  if (normalized.includes(":")) {
    return null;
  }

  const dashSplit = normalized.split(/\s*[-–]\s*/).map((part) => part.trim()).filter(Boolean);
  if (dashSplit.length === 2 && dashSplit.every((part) => part.split(" ").length >= 2)) {
    return dashSplit;
  }

  const suffixes = [" Röd", " Blå", " Vit", " Svart", " Gul", " Grön", " HF", " HK", " IK"];
  for (const suffix of suffixes) {
    const index = normalized.indexOf(suffix);
    if (index > 0) {
      const left = normalized.slice(0, index + suffix.length).trim();
      const right = normalized.slice(index + suffix.length).trim();
      if (left && right && left.split(" ").length >= 2 && right.split(" ").length >= 2) {
        return [left, right];
      }
    }
  }

  const tokenPatterns = [
    /^(.*?\b(?:Röd|Blå|Vit|Svart|Gul|Grön)\b)\s+(.*)$/,
    /^(.*?\b(?:HF|HK|IK)\b)\s+(.*)$/,
  ];
  for (const pattern of tokenPatterns) {
    const match = normalized.match(pattern);
    if (match && match[1] && match[2] && match[1].split(" ").length >= 2 && match[2].split(" ").length >= 2) {
      return [match[1].trim(), match[2].trim()];
    }
  }

  return null;
}

function inferPdfTeamsFromTimelineRows(rows) {
  const teams = unique(rows.map((row) => row.teamName).filter(Boolean));
  if (teams.length !== 2) {
    return null;
  }

  const goalRows = rows.filter((row) => row.actionText && row.actionText.includes("Mål") && parsePdfScore(row.score));
  let previousScore = null;

  for (const row of goalRows) {
    const score = parsePdfScore(row.score);
    if (!score) {
      continue;
    }

    if (!previousScore) {
      if (score.home === 1 && score.away === 0) {
        return [row.teamName, teams.find((team) => team !== row.teamName)];
      }
      if (score.home === 0 && score.away === 1) {
        return [teams.find((team) => team !== row.teamName), row.teamName];
      }
      previousScore = score;
      continue;
    }

    const homeDelta = score.home - previousScore.home;
    const awayDelta = score.away - previousScore.away;

    if (homeDelta === 1 && awayDelta === 0) {
      return [row.teamName, teams.find((team) => team !== row.teamName)];
    }
    if (homeDelta === 0 && awayDelta === 1) {
      return [teams.find((team) => team !== row.teamName), row.teamName];
    }

    previousScore = score;
  }

  return [teams[0], teams[1]];
}

function buildPdfTimelineRows(rows) {
  const rowsByPage = new Map();

  rows.forEach((row) => {
    const pageRows = rowsByPage.get(row.page ?? 0) ?? [];
    pageRows.push(row);
    rowsByPage.set(row.page ?? 0, pageRows);
  });

  return [...rowsByPage.entries()]
    .sort((left, right) => left[0] - right[0])
    .flatMap(([, pageRows]) => {
      const grouped = new Map();

      pageRows.forEach((row) => {
        const yKey = Math.round(row.y * 10) / 10;
        const bucket = grouped.get(yKey) ?? [];
        bucket.push(row);
        grouped.set(yKey, bucket);
      });

      return [...grouped.entries()]
        .sort((left, right) => right[0] - left[0])
        .map(([, columns]) => columns.sort((left, right) => left.x - right.x))
        .map((columns) => mapPdfColumnsToRow(columns))
        .filter((row) => row && row.time && row.actionText && row.actionText !== "Händelse");
    });
}

function mapPdfColumnsToRow(columns) {
  const row = {
    time: null,
    score: null,
    teamName: null,
    actionText: null,
    playerNumber: null,
    playerName: null,
  };

  columns.forEach((column) => {
    if (column.x >= 70 && column.x < 100) {
      row.time = column.text;
    } else if (column.x >= 100 && column.x < 130) {
      row.score = column.text;
    } else if (column.x >= 130 && column.x < 200) {
      row.teamName = column.text;
    } else if (column.x >= 200 && column.x < 360) {
      row.actionText = column.text;
    } else if (column.x >= 360 && column.x < 395) {
      row.playerNumber = column.text;
    } else if (column.x >= 395) {
      row.playerName = column.text;
    }
  });

  if (!row.time || !/^\d+:\d{2}$/.test(row.time)) {
    return null;
  }

  return row;
}

function matchesSelectedPdfSide(rowTeamName, selectedTeamName) {
  if (!rowTeamName || !selectedTeamName) {
    return false;
  }

  const normalize = (value) => value
    .toLowerCase()
    .replace(/\.\.\.$/, "")
    .replace(/\.\.\./g, "")
    .replace(/\s+/g, " ")
    .trim();
  const rowValue = normalize(rowTeamName);
  const selectedValue = normalize(selectedTeamName);

  return selectedValue.startsWith(rowValue) || rowValue.startsWith(selectedValue) || selectedValue.includes(rowValue);
}

function inferPdfRowAction(row) {
  const text = String(row.actionText ?? "").toLowerCase();

  if (text.includes("miss")) {
    return "MISS";
  }
  if (text.includes("mål")) {
    return "GOAL";
  }
  if (text.includes("varning")) {
    return "WARNING";
  }
  if (text.includes("utvisning")) {
    return "SUSPENSION";
  }
  return "EVENT";
}

function shouldImportTimelineEntry(entry) {
  const description = String(entry.description ?? "").toLowerCase().trim();

  if (!description) {
    return false;
  }

  if (
    description === "spelare aktiverad"
    || description === "start första halvlek"
    || description === "start andra halvlek"
    || description === "matchen är slut"
    || description === "text"
    || description === "tilldömd 7-m"
  ) {
    return false;
  }

  return isSupportedImportedAction(mapImportedActionToPlay(entry));
}

function parsePdfScore(value) {
  const match = String(value ?? "").match(/^(\d+)-(\d+)$/);
  if (!match) {
    return null;
  }

  return {
    home: Number(match[1]),
    away: Number(match[2]),
  };
}

function buildPdfSortOrder(time, index) {
  const match = String(time).match(/^(\d+):(\d{2})$/);
  if (!match) {
    return index;
  }

  return Number(match[1]) * 6000 + Number(match[2]) * 100 + index;
}

function mapImportedContext(entry) {
  const description = String(entry.description ?? "").toLowerCase();

  if (description.includes("miss 7-m") || description.includes("7-m miss")) {
    return { outcome: "MISS" };
  }
  if (entry.action === "GOAL" && description.includes("7-m")) {
    return { outcome: "GOAL" };
  }
  if (entry.action === "GOAL") {
    return { outcome: "GOAL" };
  }
  if (entry.action === "WARNING") {
    return { cardType: "YELLOW" };
  }
  if (entry.action === "CARD") {
    return { cardType: "RED" };
  }
  if (entry.action === "SUSPENSION") {
    return { duration: "2 MIN" };
  }
  return {};
}

function mapImportedStatType(entry) {
  if (entry.action === "EVENT") {
    return slugifyStatLabel(entry.description ?? "EVENT");
  }
  return entry.action ?? "EVENT";
}

function buildImportedPlaySource(entry, match, teamName, matchId) {
  return [
    teamName,
    match?.matchNumber ?? matchId,
    entry.description ?? "Imported event",
  ].filter(Boolean).join(" • ");
}

function buildImportedPlayTokens(entry, context) {
  return [
    ...Object.entries(context ?? {}).map(([key, value]) => `${key}:${formatContextOption(key, value)}`),
    entry.playerNumber ? `#${entry.playerNumber}` : null,
    entry.score ? `score:${entry.score.home}-${entry.score.away}` : null,
  ].filter(Boolean);
}

function buildPlayContextTokens({ existingPlay = null, context = {}, preserveImportedMetadata = false }) {
  const contextTokens = Object.entries(context).map(([key, value]) => `${key}:${formatContextOption(key, value)}`);
  if (!preserveImportedMetadata) {
    return contextTokens;
  }

  const contextPrefixes = ["height:", "location:", "outcome:", "assistPlayerId:", "cardType:", "duration:"];
  const preservedTokens = (existingPlay.contextTokens ?? []).filter((token) => !contextPrefixes.some((prefix) => token.startsWith(prefix)));
  return [...contextTokens, ...preservedTokens];
}

function buildImportedEventDimensions(entry, match) {
  return {
    period: entry.period ?? "",
    clock: entry.displayGameTime ?? "",
    match_number: match?.matchNumber ?? "",
    player_number: entry.playerNumber ?? "",
    score: entry.score ? `${entry.score.home}-${entry.score.away}` : "",
    attack_type: String(entry.description ?? "").includes("7-m") ? "penalty" : "",
  };
}

function buildImportedPlayers(scannedPlayers, timeline, teamName) {
  const playersById = new Map();

  scannedPlayers.forEach((player) => {
    if (player?.id) {
      playersById.set(player.id, player);
    }
  });

  timeline.forEach((entry, index) => {
    const playerId = getImportedPlayerId(entry, teamName, index);
    if (!playersById.has(playerId)) {
      playersById.set(playerId, {
        id: playerId,
        number: entry.playerNumber ?? "?",
        name: entry.playerName ?? `${teamName} event`,
      });
    }

    if (entry.assistPlayerName) {
      const assistPlayerId = getImportedAssistPlayerId(entry, index);
      if (!playersById.has(assistPlayerId)) {
        playersById.set(assistPlayerId, {
          id: assistPlayerId,
          number: entry.assistPlayerNumber ?? "?",
          name: entry.assistPlayerName,
        });
      }
    }
  });

  return [...playersById.values()].sort(compareImportedPlayers);
}

function extractPdfPlayers(rows, teamName, side) {
  const playersByKey = new Map();

  rows.forEach((row, index) => {
    if (!row.playerName && !row.playerNumber) {
      return;
    }

    const entry = {
      playerId: row.playerNumber ? `pdf-${side}-${row.playerNumber}` : null,
      playerName: row.playerName || null,
      playerNumber: row.playerNumber || null,
    };
    const player = {
      id: getImportedPlayerId(entry, teamName, index),
      number: row.playerNumber ?? "?",
      name: row.playerName ?? `${teamName} player`,
    };
    playersByKey.set(`${player.number}|${player.name}`, player);
  });

  return [...playersByKey.values()].sort(compareImportedPlayers);
}

function compareImportedPlayers(left, right) {
  const leftNumber = Number(left.number);
  const rightNumber = Number(right.number);
  const leftHasNumber = Number.isFinite(leftNumber);
  const rightHasNumber = Number.isFinite(rightNumber);

  if (leftHasNumber && rightHasNumber && leftNumber !== rightNumber) {
    return leftNumber - rightNumber;
  }
  if (leftHasNumber !== rightHasNumber) {
    return leftHasNumber ? -1 : 1;
  }

  return String(left.name).localeCompare(String(right.name), "sv");
}

function getImportedPlayerId(entry, teamName, index) {
  if (entry.playerId) {
    return `profixio-player-${entry.playerId}`;
  }

  if (entry.playerName) {
    return `profixio-player-${slugifyIdentifier(`${entry.playerName}-${entry.playerNumber ?? index}`)}`;
  }

  return `profixio-player-${slugifyIdentifier(`${teamName}-event-${entry.eventId ?? index}`)}`;
}

function getImportedAssistPlayerId(entry, index) {
  if (entry.assistPlayerId) {
    return `profixio-player-${entry.assistPlayerId}`;
  }

  return `profixio-player-${slugifyIdentifier(`${entry.assistPlayerName ?? "assist"}-${entry.assistPlayerNumber ?? index}`)}`;
}

function normalizeImportedTimestamp(createdAt, fallbackIso, index) {
  const iso = createdAt ?? fallbackIso;
  const parsed = iso ? new Date(iso) : new Date();
  if (!Number.isNaN(parsed.getTime())) {
    return parsed;
  }

  return new Date(Date.now() + index * 1000);
}

function slugifyStatLabel(value) {
  return String(value)
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .toUpperCase() || "EVENT";
}

function slugifyIdentifier(value) {
  return String(value)
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .toLowerCase() || crypto.randomUUID();
}

function unique(values) {
  return [...new Set(values)];
}

function formatPdfDebug(debug) {
  return [
    `file=${debug.fileName ?? "(unknown)"}`,
    `size=${debug.fileSize ?? "(unknown)"}`,
    `streams=${debug.streamCount ?? "(unknown)"}`,
    `decompressed=${debug.decompressedCount ?? "(unknown)"}`,
    `text_blocks=${debug.matchedTextBlocks ?? "(unknown)"}`,
    `parsed_rows=${debug.parsedTimelineRows ?? "(unknown)"}`,
    `header_rows=${debug.headerRows ?? "(unknown)"}`,
    `preview=${debug.mergedPreview ?? "(unknown)"}`,
  ].join("\n");
}

function loadPlayIntoEditor(playId) {
  const play = state.plays.find((entry) => entry.id === playId);
  if (!play || play.editable === false) {
    return;
  }

  state.selectedPlayerId = play.playerId;
  state.selectedActionId = play.actionId;
  state.context = filterContextForAction(play.actionId, play.context);
  state.editingPlayId = play.id;
  state.currentStageIndex = Math.max(0, getFlowStages(play.actionId).length - 1);
  render();
}

function deletePlay(playId) {
  state.plays = state.plays.filter((play) => play.id !== playId);
  state.events = state.events.filter((event) => event.playId !== playId);

  if (state.editingPlayId === playId) {
    resetFlow();
    return;
  }

  render();
}

function playerLabelFromId(playerId) {
  const player = players.find((entry) => entry.id === playerId);
  return player ? player.name : playerId;
}

function formatContextOption(key, value) {
  if (key === "assistPlayerId" && value !== "NONE") {
    return playerLabelFromId(value);
  }

  return translations[state.language].optionLabel[value]
    ?? value
      .toLowerCase()
      .replaceAll("_", " ")
      .replace(/\b\w/g, (character) => character.toUpperCase());
}

function formatDimensionValue(key, value) {
  if (key === "target_player") {
    return value;
  }

  return translations[state.language].optionLabel[String(value).toUpperCase()]
    ?? String(value).replaceAll("_", " ");
}

function t(key, variables = {}) {
  const template = translations[state.language][key] ?? key;
  return Object.entries(variables).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

function setLanguage(language) {
  if (state.language === language) {
    return;
  }

  state.language = language;
  render();
}

function isMobileViewport() {
  return window.matchMedia("(max-width: 720px)").matches;
}

function formatTime(date) {
  return date.toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function filterContextForAction(actionId, context) {
  return Object.fromEntries(
    Object.entries(context).filter(([key]) => isContextEnabled(actionId, key)),
  );
}
