const players = Array.from({ length: 16 }, (_, index) => ({
  id: `p${index + 1}`,
  number: index + 1,
  name: `Player ${index + 1}`,
}));

const translations = {
  "en-US": {
    appTitle: "Handball Scout Pad",
    heroEyebrow: "Live handball scouting",
    heroTitle: "Track primary actions. Derive the rest.",
    heroCopy: "A tablet-first entry surface built around player selection, action buttons, and context prompts.",
    playCountLabel: "Plays",
    eventCountLabel: "Derived events",
    entryPadTitle: "Entry Pad",
    resetFlow: "Reset flow",
    startActionTitle: "Start Action",
    startActionCopy: "All primary actions stay available from the first screen.",
    guidedFlow: "Guided Flow",
    guidedFlowCopy: "Pick an action to start the staged entry flow.",
    waitingForAction: "Waiting for action",
    selectPrimaryAction: "Select a primary action above to begin.",
    back: "Back",
    next: "Next",
    recordPlay: "Record play",
    saveChanges: "Save changes",
    liveStateTitle: "Live match state",
    addDemoSequence: "Add demo sequence",
    recordedPlaysTitle: "Recorded plays",
    derivedEventsTitle: "Derived events",
    autoGenerated: "Auto-generated",
    noPlaysYet: "No plays yet",
    playLogEmpty: "Record a play to start building the match timeline.",
    eventLogEmpty: "Derived stat events will appear here.",
    settingsTitle: "Flow settings",
    settingsCopy: "Choose which context steps should appear for each action.",
    openSettings: "Open settings",
    closeSettings: "Close settings",
    modeEditing: "Editing existing play",
    modeCreating: "Creating new play",
    notSelected: "Not selected",
    noContextSelected: "No context selected",
    stepOf: "Step {current} of {total}",
    choosePlayer: "Choose player",
    choosePlayerCopy: "Select the player responsible for this action.",
    settingsGroupCopy: "Choose which context steps should appear in the guided flow.",
    displaySettingsTitle: "Display",
    displaySettingsCopy: "Control how actions are presented in the entry pad.",
    showActionIcons: "Show action icons",
    toggleOn: "On",
    toggleOff: "Off",
    noConfigurableContext: "No configurable context groups available.",
    edit: "Edit",
    editing: "Editing",
    delete: "Delete",
    flowSuffix: "flow",
    captureContext: "Capture {label} before recording the play.",
    metricGoals: "Goals",
    metricGoalsCaption: "Derived from shot outcomes and scoring events",
    metricShotsOnGoal: "Shots on goal",
    metricShotsOnGoalCaption: "Goals and saves",
    metricShotEfficiency: "Shot efficiency",
    metricShotEfficiencyCaption: "Goals divided by total shots",
    metricKeeperSaves: "Keeper saves",
    metricKeeperSavesCaption: "Auto-created or manual goalkeeper saves",
    metricPenaltyGoals: "Penalty goals",
    metricPenaltyGoalsCaption: "Goals tagged as penalties",
    metricWarnings: "Warnings",
    metricWarningsCaption: "Cards mapped to warning events",
    summaryMode: "MODE",
    summaryPlayer: "PLAYER",
    summaryAction: "ACTION",
    summaryContext: "CONTEXT",
    action: {
      SHOT: { label: "Shot", description: "Creates shot and outcome events" },
      PENALTY: { label: "Penalty", description: "Records a 7m attempt and outcome" },
      SAVE: { label: "Save", description: "Manual goalkeeper save entry" },
      MISS: { label: "Miss", description: "Manual missed attempt" },
      TECH_FAULT: { label: "Tech Fault", description: "Turnover or handling fault" },
      STEAL: { label: "Steal", description: "Defensive possession win" },
      BLOCK: { label: "Block", description: "Blocked attacking action" },
      CARD: { label: "Card", description: "Warning or discipline event" },
      SUSPENSION: { label: "Suspension", description: "Timed exclusion" },
    },
    contextLabel: {
      height: "Height",
      location: "Location",
      outcome: "Outcome",
      assistPlayerId: "Assist",
      cardType: "Card type",
      duration: "Duration",
    },
    optionLabel: {
      HIGH: "High",
      LOW: "Low",
      WING: "Wing",
      BACKCOURT: "Backcourt",
      LINE: "Line",
      BREAKTHROUGH: "Breakthrough",
      FAST_BREAK: "Fast break",
      PENALTY: "Penalty",
      GOAL: "Goal",
      SAVE: "Save",
      MISS: "Miss",
      BLOCK: "Block",
      NONE: "No assist",
      YELLOW: "Yellow",
      RED: "Red",
      "2 MIN": "2 min",
    },
  },
  "sv-SE": {
    appTitle: "Handboll Scout Pad",
    heroEyebrow: "Live scouting i handboll",
    heroTitle: "Registrera grundhändelser. Härled resten.",
    heroCopy: "En surfplatteanpassad registreringsyta byggd kring spelare, händelseknappar och kontextsteg.",
    playCountLabel: "Spel",
    eventCountLabel: "Härledda händelser",
    entryPadTitle: "Inmatning",
    resetFlow: "Återställ",
    startActionTitle: "Starta händelse",
    startActionCopy: "Alla primära händelser finns tillgängliga direkt från första vyn.",
    guidedFlow: "Stegvis flöde",
    guidedFlowCopy: "Välj en händelse för att starta det stegvisa flödet.",
    waitingForAction: "Väntar på händelse",
    selectPrimaryAction: "Välj en primär händelse ovan för att börja.",
    back: "Tillbaka",
    next: "Nästa",
    recordPlay: "Registrera",
    saveChanges: "Spara ändringar",
    liveStateTitle: "Matchläge live",
    addDemoSequence: "Lägg till demo",
    recordedPlaysTitle: "Registrerade spel",
    derivedEventsTitle: "Härledda händelser",
    autoGenerated: "Automatiskt skapade",
    noPlaysYet: "Inga spel ännu",
    playLogEmpty: "Registrera ett spel för att börja bygga matchtidslinjen.",
    eventLogEmpty: "Härledda statistik-händelser visas här.",
    settingsTitle: "Flödesinställningar",
    settingsCopy: "Välj vilka kontextsteg som ska visas för varje händelse.",
    openSettings: "Öppna inställningar",
    closeSettings: "Stäng inställningar",
    modeEditing: "Redigerar befintligt spel",
    modeCreating: "Skapar nytt spel",
    notSelected: "Inte vald",
    noContextSelected: "Ingen kontext vald",
    stepOf: "Steg {current} av {total}",
    choosePlayer: "Välj spelare",
    choosePlayerCopy: "Välj spelaren som ansvarar för händelsen.",
    settingsGroupCopy: "Välj vilka kontextsteg som ska visas i det stegvisa flödet.",
    displaySettingsTitle: "Visning",
    displaySettingsCopy: "Styr hur händelser visas i inmatningsytan.",
    showActionIcons: "Visa händelseikoner",
    toggleOn: "På",
    toggleOff: "Av",
    noConfigurableContext: "Inga konfigurerbara kontextsteg finns.",
    edit: "Redigera",
    editing: "Redigerar",
    delete: "Ta bort",
    flowSuffix: "flöde",
    captureContext: "Registrera {label} innan spelet sparas.",
    metricGoals: "Mål",
    metricGoalsCaption: "Härleds från skottutfall och mål-händelser",
    metricShotsOnGoal: "Skott på mål",
    metricShotsOnGoalCaption: "Mål och räddningar",
    metricShotEfficiency: "Skotteffektivitet",
    metricShotEfficiencyCaption: "Mål dividerat med antal skott",
    metricKeeperSaves: "Målvaktsräddningar",
    metricKeeperSavesCaption: "Automatiska eller manuella målvaktsräddningar",
    metricPenaltyGoals: "Straffmål",
    metricPenaltyGoalsCaption: "Mål märkta som straffar",
    metricWarnings: "Varningar",
    metricWarningsCaption: "Kort mappas till varningshändelser",
    summaryMode: "LÄGE",
    summaryPlayer: "SPELARE",
    summaryAction: "HÄNDELSE",
    summaryContext: "KONTEXT",
    action: {
      SHOT: { label: "Skott", description: "Skapar skott- och utfallshändelser" },
      PENALTY: { label: "Straff", description: "Registrerar ett 7 m-försök och utfall" },
      SAVE: { label: "Räddning", description: "Manuell registrering av målvaktsräddning" },
      MISS: { label: "Miss", description: "Manuellt registrerat missat avslut" },
      TECH_FAULT: { label: "Tekniskt fel", description: "Bolltapp eller tekniskt fel" },
      STEAL: { label: "Stöld", description: "Defensivt bollvinst" },
      BLOCK: { label: "Block", description: "Blockerad anfallshändelse" },
      CARD: { label: "Kort", description: "Varning eller disciplinhändelse" },
      SUSPENSION: { label: "Utvisning", description: "Tidsbegränsad utvisning" },
    },
    contextLabel: {
      height: "Höjd",
      location: "Position",
      outcome: "Utfall",
      assistPlayerId: "Assist",
      cardType: "Korttyp",
      duration: "Längd",
    },
    optionLabel: {
      HIGH: "Hög",
      LOW: "Låg",
      WING: "Kant",
      BACKCOURT: "Nio meter",
      LINE: "Linje",
      BREAKTHROUGH: "Genombrott",
      FAST_BREAK: "Kontring",
      PENALTY: "Straff",
      GOAL: "Mål",
      SAVE: "Räddning",
      MISS: "Miss",
      BLOCK: "Block",
      NONE: "Ingen assist",
      YELLOW: "Gult",
      RED: "Rött",
      "2 MIN": "2 min",
    },
  },
};

const actionIcons = {
  SHOT: "◎",
  PENALTY: "7m",
  SAVE: "◐",
  MISS: "○",
  TECH_FAULT: "!",
  STEAL: "↺",
  BLOCK: "■",
  CARD: "▮",
  SUSPENSION: "2'",
};

const actionDefinitions = [
  { id: "SHOT", label: "Shot", description: "Creates shot and outcome events" },
  { id: "PENALTY", label: "Penalty", description: "Records a 7m attempt and outcome" },
  { id: "SAVE", label: "Save", description: "Manual goalkeeper save entry" },
  { id: "MISS", label: "Miss", description: "Manual missed attempt" },
  { id: "TECH_FAULT", label: "Tech Fault", description: "Turnover or handling fault" },
  { id: "STEAL", label: "Steal", description: "Defensive possession win" },
  { id: "BLOCK", label: "Block", description: "Blocked attacking action" },
  { id: "CARD", label: "Card", description: "Warning or discipline event" },
  { id: "SUSPENSION", label: "Suspension", description: "Timed exclusion" },
];

const contextDefinitions = {
  SHOT: [
    { key: "height", label: "Height", options: ["HIGH", "LOW"] },
    { key: "location", label: "Location", options: ["WING", "BACKCOURT", "LINE", "BREAKTHROUGH", "FAST_BREAK"] },
    { key: "outcome", label: "Outcome", options: ["GOAL", "SAVE", "MISS", "BLOCK"] },
  ],
  PENALTY: [
    { key: "height", label: "Height", options: ["HIGH", "LOW"] },
    { key: "outcome", label: "Outcome", options: ["GOAL", "SAVE", "MISS", "BLOCK"] },
  ],
  SAVE: [
    { key: "height", label: "Shot height", options: ["HIGH", "LOW"] },
    { key: "location", label: "Shot source", options: ["WING", "BACKCOURT", "LINE", "BREAKTHROUGH", "PENALTY", "FAST_BREAK"] },
  ],
  MISS: [
    { key: "height", label: "Shot height", options: ["HIGH", "LOW"] },
    { key: "location", label: "Shot source", options: ["WING", "BACKCOURT", "LINE", "BREAKTHROUGH", "PENALTY", "FAST_BREAK"] },
  ],
  CARD: [
    { key: "cardType", label: "Card type", options: ["YELLOW", "RED"] },
  ],
  SUSPENSION: [
    { key: "duration", label: "Duration", options: ["2 MIN"] },
  ],
};

const contextSettings = Object.fromEntries(
  Object.entries(contextDefinitions).map(([actionId, groups]) => [
    actionId,
    Object.fromEntries(groups.map((group) => [group.key, true])),
  ]),
);

["SHOT", "PENALTY"].forEach((actionId) => {
  contextSettings[actionId].assistPlayerId = true;
});

const state = {
  language: "en-US",
  showActionIcons: true,
  selectedPlayerId: null,
  selectedActionId: null,
  context: {},
  editingPlayId: null,
  currentStageIndex: 0,
  contextSettings,
  plays: [],
  events: [],
};

const actionGrid = document.querySelector("#action-grid");
const actionStepCard = document.querySelector("#action-step-card");
const flowTitle = document.querySelector("#flow-title");
const flowCopy = document.querySelector("#flow-copy");
const flowProgress = document.querySelector("#flow-progress");
const flowStageLabel = document.querySelector("#flow-stage-label");
const flowCard = document.querySelector("#flow-card");
const stageHost = document.querySelector("#stage-host");
const selectionSummary = document.querySelector("#selection-summary");
const backStepButton = document.querySelector("#back-step");
const nextStepButton = document.querySelector("#next-step");
const commitButton = document.querySelector("#commit-play");
const playLog = document.querySelector("#play-log");
const eventLog = document.querySelector("#event-log");
const toggleSettingsButton = document.querySelector("#toggle-settings");
const closeSettingsButton = document.querySelector("#close-settings");
const settingsDialog = document.querySelector("#settings-dialog");
const settingsPanel = document.querySelector("#settings-panel");
const playCount = document.querySelector("#play-count");
const eventCount = document.querySelector("#event-count");
const metricsGrid = document.querySelector("#metrics-grid");
const lastPlayLabel = document.querySelector("#last-play-label");
const langEnButton = document.querySelector("#lang-en");
const langSvButton = document.querySelector("#lang-sv");

let lastFlowViewportKey = "";

document.querySelector("#reset-flow").addEventListener("click", resetFlow);
document.querySelector("#commit-play").addEventListener("click", commitPlay);
document.querySelector("#seed-demo").addEventListener("click", seedDemoSequence);
toggleSettingsButton.addEventListener("click", openSettingsDialog);
closeSettingsButton.addEventListener("click", closeSettingsDialog);
backStepButton.addEventListener("click", goToPreviousStage);
nextStepButton.addEventListener("click", goToNextStage);
settingsDialog.addEventListener("close", renderSettingsButtonState);
settingsDialog.addEventListener("click", handleDialogBackdropClick);
langEnButton.addEventListener("click", () => setLanguage("en-US"));
langSvButton.addEventListener("click", () => setLanguage("sv-SE"));

render();

function render() {
  renderChromeText();
  renderActions();
  normalizeFlowState();
  renderFlow();
  renderMetrics();
  renderSettingsButtonState();
  renderSettings();
  renderPlayLog();
  renderEventLog();
  playCount.textContent = String(state.plays.length);
  eventCount.textContent = String(state.events.length);
  syncMobileFlowViewport();
}

function renderChromeText() {
  document.documentElement.lang = state.language === "sv-SE" ? "sv" : "en";
  document.title = t("appTitle");
  document.querySelector("#hero-eyebrow").textContent = t("heroEyebrow");
  document.querySelector("#hero-title").textContent = t("heroTitle");
  document.querySelector("#hero-copy").textContent = t("heroCopy");
  document.querySelector("#play-count-label").textContent = t("playCountLabel");
  document.querySelector("#event-count-label").textContent = t("eventCountLabel");
  document.querySelector("#entry-pad-title").textContent = t("entryPadTitle");
  document.querySelector("#reset-flow").textContent = t("resetFlow");
  document.querySelector("#start-action-title").textContent = t("startActionTitle");
  document.querySelector("#start-action-copy").textContent = t("startActionCopy");
  document.querySelector("#live-state-title").textContent = t("liveStateTitle");
  document.querySelector("#seed-demo").textContent = t("addDemoSequence");
  document.querySelector("#recorded-plays-title").textContent = t("recordedPlaysTitle");
  document.querySelector("#derived-events-title").textContent = t("derivedEventsTitle");
  document.querySelector("#derived-events-pill").textContent = t("autoGenerated");
  document.querySelector("#settings-title").textContent = t("settingsTitle");
  document.querySelector("#settings-copy").textContent = t("settingsCopy");
  document.querySelector("#toggle-settings").setAttribute("aria-label", t("openSettings"));
  document.querySelector("#close-settings").setAttribute("aria-label", t("closeSettings"));
  backStepButton.textContent = t("back");
  nextStepButton.textContent = t("next");
  langEnButton.classList.toggle("is-active", state.language === "en-US");
  langSvButton.classList.toggle("is-active", state.language === "sv-SE");
}

function renderActions() {
  actionGrid.innerHTML = "";

  actionDefinitions.forEach((action) => {
    const button = document.createElement("button");
    button.type = "button";
    button.className = [
      "select-button",
      state.selectedActionId === action.id ? "is-selected" : "",
    ].join(" ").trim();
    button.innerHTML = `
      ${renderActionButtonContent(action.id)}
      <small>${getActionDescription(action.id)}</small>
    `;
    button.addEventListener("click", () => {
      const isSameAction = state.selectedActionId === action.id;
      state.selectedActionId = action.id;
      state.context = isSameAction ? state.context : {};
      state.currentStageIndex = 0;
      render();
    });
    actionGrid.appendChild(button);
  });
}

function renderFlow() {
  renderSummary();
  const stages = getFlowStages();

  if (!state.selectedActionId) {
    flowTitle.textContent = t("guidedFlow");
    flowCopy.textContent = t("guidedFlowCopy");
    flowProgress.innerHTML = "";
    flowStageLabel.textContent = t("waitingForAction");
    stageHost.className = "stage-host empty-state";
    stageHost.textContent = t("selectPrimaryAction");
    backStepButton.disabled = true;
    nextStepButton.disabled = true;
    commitButton.disabled = true;
    commitButton.textContent = state.editingPlayId ? t("saveChanges") : t("recordPlay");
    return;
  }

  const activeIndex = Math.min(state.currentStageIndex, Math.max(0, stages.length - 1));
  state.currentStageIndex = activeIndex;
  const activeStage = stages[activeIndex];

  flowTitle.textContent = `${getActionLabel(state.selectedActionId)} ${t("flowSuffix")}`;
  flowCopy.textContent = activeStage.description;
  flowStageLabel.textContent = t("stepOf", { current: activeIndex + 1, total: stages.length });
  flowProgress.innerHTML = stages
    .map((stage, index) => {
      const classes = [
        "progress-pill",
        index === activeIndex ? "is-active" : "",
        isStageComplete(stage) ? "is-complete" : "",
      ].filter(Boolean).join(" ");
      return `<span class="${classes}">${stage.shortLabel}</span>`;
    })
    .join("");

  stageHost.className = "stage-host";
  stageHost.innerHTML = "";
  renderStage(activeStage);

  backStepButton.disabled = activeIndex === 0;
  nextStepButton.disabled = activeIndex >= stages.length - 1 || !isStageComplete(activeStage);
  commitButton.disabled = !isFlowComplete();
  commitButton.textContent = state.editingPlayId ? t("saveChanges") : t("recordPlay");
}

function syncMobileFlowViewport() {
  if (!isMobileViewport()) {
    lastFlowViewportKey = "";
    return;
  }

  const viewportKey = state.selectedActionId
    ? `${state.selectedActionId}:${state.currentStageIndex}:${state.selectedPlayerId ?? "none"}:${state.context.outcome ?? "none"}`
    : "idle";

  if (viewportKey === lastFlowViewportKey) {
    return;
  }

  lastFlowViewportKey = viewportKey;

  const target = state.selectedActionId ? flowCard : actionStepCard;
  window.requestAnimationFrame(() => {
    target.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  });
}

function renderStage(stage) {
  const wrapper = document.createElement("div");
  wrapper.className = "context-group stage-group";

  const label = document.createElement("p");
  label.className = "context-group-label";
  label.textContent = stage.label;
  wrapper.appendChild(label);

  const caption = document.createElement("p");
  caption.className = "stage-copy";
  caption.textContent = stage.description;
  wrapper.appendChild(caption);

  const options = document.createElement("div");
  options.className = stage.type === "player" ? "player-grid" : "context-options";

  if (stage.type === "player") {
    players.forEach((player) => {
      const button = document.createElement("button");
      button.type = "button";
      button.className = `select-button ${state.selectedPlayerId === player.id ? "is-selected" : ""}`.trim();
      button.innerHTML = `#${player.number}<small>${player.name}</small>`;
      button.addEventListener("click", () => {
        state.selectedPlayerId = player.id;
        render();
      });
      options.appendChild(button);
    });
  } else {
    stage.options.forEach((option) => {
      const button = document.createElement("button");
      button.type = "button";
      const isSelected = state.context[stage.key] === option;
      button.className = `select-button ${isSelected ? "is-selected" : ""}`.trim();
      button.textContent = formatContextOption(stage.key, option);
      button.addEventListener("click", () => {
        state.context[stage.key] = option;
        render();
      });
      options.appendChild(button);
    });
  }

  wrapper.appendChild(options);
  stageHost.appendChild(wrapper);
}

function renderSummary() {
  const player = getSelectedPlayer();
  const action = state.selectedActionId ? getActionLabel(state.selectedActionId) : "None";
  const parts = [
    `${t("summaryMode")}: ${state.editingPlayId ? t("modeEditing") : t("modeCreating")}`,
    `${t("summaryPlayer")}: ${player ? `#${player.number} ${player.name}` : t("notSelected")}`,
    `${t("summaryAction")}: ${action ?? t("notSelected")}`,
  ];

  const contextEntries = Object.entries(state.context);
  if (contextEntries.length) {
    contextEntries.forEach(([key, value]) => {
      parts.push(`${getContextLabel(key).toUpperCase()}: ${formatContextOption(key, value)}`);
    });
  } else {
    parts.push(`${t("summaryContext")}: ${t("noContextSelected")}`);
  }

  selectionSummary.innerHTML = parts.join("<br>");
}

function renderMetrics() {
  const summary = calculateSummary(state.events);
  const cards = [
    { label: t("metricGoals"), value: summary.goals, caption: t("metricGoalsCaption") },
    { label: t("metricShotsOnGoal"), value: summary.shotsOnGoal, caption: t("metricShotsOnGoalCaption") },
    { label: t("metricShotEfficiency"), value: `${summary.shotEfficiency}%`, caption: t("metricShotEfficiencyCaption") },
    { label: t("metricKeeperSaves"), value: summary.keeperSaves, caption: t("metricKeeperSavesCaption") },
    { label: t("metricPenaltyGoals"), value: summary.penaltyGoals, caption: t("metricPenaltyGoalsCaption") },
    { label: t("metricWarnings"), value: summary.warnings, caption: t("metricWarningsCaption") },
  ];

  metricsGrid.innerHTML = "";
  cards.forEach((card) => {
    const node = document.createElement("article");
    node.className = "metric-card";
    node.innerHTML = `
      <span class="stat-label">${card.label}</span>
      <strong class="metric-value">${card.value}</strong>
      <p class="metric-caption">${card.caption}</p>
    `;
    metricsGrid.appendChild(node);
  });
}

function renderSettings() {
  settingsPanel.innerHTML = "";

  if (!Object.keys(contextSettings).length) {
    settingsPanel.className = "settings-panel empty-state";
    settingsPanel.textContent = t("noConfigurableContext");
    return;
  }

  settingsPanel.className = "settings-panel";

  const displayCard = document.createElement("article");
  displayCard.className = "settings-card";
  displayCard.innerHTML = `
    <div class="settings-card-header">
      <div>
        <p class="log-item-title">${t("displaySettingsTitle")}</p>
        <p class="log-item-subtitle">${t("displaySettingsCopy")}</p>
      </div>
    </div>
  `;

  const displayToggleRow = document.createElement("div");
  displayToggleRow.className = "settings-toggle-list";
  const iconToggle = document.createElement("button");
  iconToggle.type = "button";
  iconToggle.className = `settings-toggle ${state.showActionIcons ? "is-enabled" : "is-disabled"}`.trim();
  iconToggle.innerHTML = `
    <span>${t("showActionIcons")}</span>
    <strong>${state.showActionIcons ? t("toggleOn") : t("toggleOff")}</strong>
  `;
  iconToggle.addEventListener("click", () => {
    state.showActionIcons = !state.showActionIcons;
    render();
  });
  displayToggleRow.appendChild(iconToggle);
  displayCard.appendChild(displayToggleRow);
  settingsPanel.appendChild(displayCard);

  Object.keys(contextSettings).forEach((actionId) => {
    const groups = Object.keys(state.contextSettings[actionId]).map((key) => ({ key, label: getContextLabel(key) }));
    const card = document.createElement("article");
    card.className = "settings-card";

    const heading = document.createElement("div");
    heading.className = "settings-card-header";
    heading.innerHTML = `
      <div>
        <p class="log-item-title">${getActionLabel(actionId)}</p>
        <p class="log-item-subtitle">${t("settingsGroupCopy")}</p>
      </div>
    `;
    card.appendChild(heading);

    const toggleRow = document.createElement("div");
    toggleRow.className = "settings-toggle-list";

    groups.forEach((group) => {
      const button = document.createElement("button");
      button.type = "button";
      const isEnabled = isContextEnabled(actionId, group.key);
      button.className = `settings-toggle ${isEnabled ? "is-enabled" : "is-disabled"}`.trim();
      button.innerHTML = `
        <span>${group.label}</span>
        <strong>${isEnabled ? t("toggleOn") : t("toggleOff")}</strong>
      `;
      button.addEventListener("click", () => {
        toggleContextSetting(actionId, group.key);
      });
      toggleRow.appendChild(button);
    });

    card.appendChild(toggleRow);
    settingsPanel.appendChild(card);
  });
}

function renderSettingsButtonState() {
  const isOpen = settingsDialog.open;
  toggleSettingsButton.setAttribute("aria-expanded", String(isOpen));
  toggleSettingsButton.classList.toggle("is-active", isOpen);
}

function renderPlayLog() {
  if (!state.plays.length) {
    playLog.className = "log-list empty-state";
    playLog.textContent = t("playLogEmpty");
    lastPlayLabel.textContent = t("noPlaysYet");
    return;
  }

  playLog.className = "log-list";
  playLog.innerHTML = "";
  const latestPlay = state.plays[state.plays.length - 1];
  lastPlayLabel.textContent = latestPlay.timeLabel;

  state.plays.slice().reverse().forEach((play) => {
    const item = document.createElement("article");
    item.className = "log-item";
    const isEditing = state.editingPlayId === play.id;
    item.innerHTML = `
      <p class="log-item-title">${formatPlayLabel(play.actionId, buildPlayTitle(play))}</p>
      <p class="log-item-subtitle">${play.timeLabel} • ${buildPlaySource(play)}</p>
      <div class="token-row">${play.contextTokens.map((token) => `<span class="token">${token}</span>`).join("")}</div>
      <div class="action-row">
        <button class="ghost-button log-action" type="button" data-action="edit">${isEditing ? t("editing") : t("edit")}</button>
        <button class="ghost-button log-action log-action-danger" type="button" data-action="delete">${t("delete")}</button>
      </div>
    `;

    item.querySelector('[data-action="edit"]').addEventListener("click", () => {
      loadPlayIntoEditor(play.id);
    });
    item.querySelector('[data-action="delete"]').addEventListener("click", () => {
      deletePlay(play.id);
    });
    playLog.appendChild(item);
  });
}

function renderEventLog() {
  if (!state.events.length) {
    eventLog.className = "log-list empty-state";
    eventLog.textContent = t("eventLogEmpty");
    return;
  }

  eventLog.className = "log-list";
  eventLog.innerHTML = "";

  state.events.slice().reverse().forEach((event) => {
    const item = document.createElement("article");
    item.className = "log-item";
    const dimensions = Object.entries(event.dimensions)
      .map(([key, value]) => `${key}=${formatDimensionValue(key, value)}`);

    item.innerHTML = `
      <p class="log-item-title">${event.statType}</p>
      <p class="log-item-subtitle">${event.playerLabel} • ${event.timeLabel}</p>
      <div class="token-row">${dimensions.map((token) => `<span class="token">${token}</span>`).join("")}</div>
    `;
    eventLog.appendChild(item);
  });
}

function commitPlay() {
  if (!isFlowComplete()) {
    return;
  }

  const player = getSelectedPlayer();
  const actionId = state.selectedActionId;
  const existingPlay = state.editingPlayId
    ? state.plays.find((play) => play.id === state.editingPlayId) ?? null
    : null;
  const playId = existingPlay?.id ?? crypto.randomUUID();
  const timestamp = existingPlay ? new Date(existingPlay.time) : new Date();
  const derivedEvents = deriveEvents({
    playId,
    player,
    actionId,
    context: { ...state.context },
    timestamp,
  });

  const play = {
    id: playId,
    gameId: "demo-game",
    time: timestamp.toISOString(),
    timeLabel: formatTime(timestamp),
    playerId: player.id,
    actionId,
    context: { ...state.context },
    sourceText: `${player.name} -> ${actionId}`,
    label: `${player.name} ${actionId.replace("_", " ")}`,
    contextTokens: Object.entries(state.context).map(([key, value]) => `${key}:${formatContextOption(key, value)}`),
  };

  if (existingPlay) {
    const playIndex = state.plays.findIndex((entry) => entry.id === existingPlay.id);
    state.plays[playIndex] = play;
    state.events = state.events.filter((event) => event.playId !== existingPlay.id);
    state.events.push(...derivedEvents);
  } else {
    state.plays.push(play);
    state.events.push(...derivedEvents);
  }

  resetFlow();
  render();
}

function resetFlow() {
  state.selectedPlayerId = null;
  state.selectedActionId = null;
  state.context = {};
  state.editingPlayId = null;
  state.currentStageIndex = 0;
  render();
}

function getContextGroups(actionId) {
  if (!actionId) {
    return [];
  }

  const groups = (contextDefinitions[actionId] ?? []).filter((group) => isContextEnabled(actionId, group.key));

  if (["SHOT", "PENALTY"].includes(actionId) && state.context.outcome === "GOAL" && isContextEnabled(actionId, "assistPlayerId")) {
    groups.push({
      key: "assistPlayerId",
      label: getContextLabel("assistPlayerId"),
      options: ["NONE", ...players.filter((player) => player.id !== state.selectedPlayerId).map((player) => player.id)],
    });
  }

  return groups;
}

function getFlowStages(actionId = state.selectedActionId) {
  if (!actionId) {
    return [];
  }

  return [
    {
      type: "player",
      key: "player",
      label: t("choosePlayer"),
      shortLabel: t("choosePlayer"),
      description: t("choosePlayerCopy"),
    },
    ...getContextGroups(actionId).map((group) => ({
      type: "context",
      key: group.key,
      label: getContextLabel(group.key),
      shortLabel: getContextLabel(group.key),
      description: t("captureContext", { label: getContextLabel(group.key).toLowerCase() }),
      options: group.options,
    })),
  ];
}

function getCurrentStage() {
  const stages = getFlowStages();
  if (!stages.length) {
    return null;
  }

  return stages[Math.min(state.currentStageIndex, stages.length - 1)];
}

function normalizeFlowState() {
  if (!state.selectedActionId) {
    return;
  }

  const stages = getFlowStages();
  if (!stages.length) {
    state.currentStageIndex = 0;
    return;
  }

  state.currentStageIndex = Math.min(state.currentStageIndex, stages.length - 1);

  for (let index = state.currentStageIndex; index < stages.length; index += 1) {
    const stage = stages[index];

    if (stage.type === "player") {
      if (!state.selectedPlayerId) {
        state.currentStageIndex = index;
        return;
      }
      continue;
    }

    if (state.context[stage.key]) {
      continue;
    }

    if (stage.options.length !== 1) {
      state.currentStageIndex = index;
      return;
    }

    state.context[stage.key] = stage.options[0];
  }

  state.currentStageIndex = stages.length - 1;
}

function isContextEnabled(actionId, key) {
  return Boolean(state.contextSettings[actionId]?.[key]);
}

function toggleContextSetting(actionId, key) {
  const nextValue = !state.contextSettings[actionId][key];
  state.contextSettings[actionId][key] = nextValue;

  if (!nextValue) {
    delete state.context[key];
  }

  if (state.selectedActionId === actionId) {
    const stages = getFlowStages(actionId);
    state.currentStageIndex = Math.min(state.currentStageIndex, Math.max(0, stages.length - 1));
  }

  render();
}

function openSettingsDialog() {
  if (!settingsDialog.open) {
    settingsDialog.showModal();
  }
  renderSettingsButtonState();
}

function closeSettingsDialog() {
  if (settingsDialog.open) {
    settingsDialog.close();
  }
  renderSettingsButtonState();
}

function handleDialogBackdropClick(event) {
  const bounds = settingsDialog.getBoundingClientRect();
  const clickedInside =
    event.clientX >= bounds.left &&
    event.clientX <= bounds.right &&
    event.clientY >= bounds.top &&
    event.clientY <= bounds.bottom;

  if (!clickedInside) {
    closeSettingsDialog();
  }
}

function isStageComplete(stage) {
  if (!stage) {
    return false;
  }

  if (stage.type === "player") {
    return Boolean(state.selectedPlayerId);
  }

  return Boolean(state.context[stage.key]);
}

function goToPreviousStage() {
  if (!state.selectedActionId) {
    return;
  }

  state.currentStageIndex = Math.max(0, state.currentStageIndex - 1);
  render();
}

function goToNextStage() {
  const currentStage = getCurrentStage();
  const stages = getFlowStages();
  if (!currentStage || !isStageComplete(currentStage)) {
    return;
  }

  state.currentStageIndex = Math.min(stages.length - 1, state.currentStageIndex + 1);
  render();
}

function renderActionButtonContent(actionId) {
  const icon = state.showActionIcons ? `<span class="action-icon">${getActionIcon(actionId)}</span>` : "";
  return `<span class="action-button-label">${icon}<span>${getActionLabel(actionId)}</span></span>`;
}

function formatPlayLabel(actionId, label) {
  return state.showActionIcons ? `${getActionIcon(actionId)} ${label}` : label;
}

function buildPlayTitle(play) {
  return `${playerLabelFromId(play.playerId)} ${getActionLabel(play.actionId)}`;
}

function buildPlaySource(play) {
  return `${playerLabelFromId(play.playerId)} -> ${getActionLabel(play.actionId)}`;
}

function getActionIcon(actionId) {
  return actionIcons[actionId] ?? "•";
}

function getActionLabel(actionId) {
  return translations[state.language].action[actionId]?.label ?? actionId;
}

function getActionDescription(actionId) {
  return translations[state.language].action[actionId]?.description ?? actionId;
}

function getContextLabel(key) {
  return translations[state.language].contextLabel[key] ?? key;
}

function getSelectedPlayer() {
  return players.find((player) => player.id === state.selectedPlayerId) ?? null;
}

function isFlowComplete() {
  if (!state.selectedPlayerId || !state.selectedActionId) {
    return false;
  }

  const groups = getContextGroups(state.selectedActionId);
  return groups.every((group) => state.context[group.key]);
}

function deriveEvents({ playId, player, actionId, context, timestamp }) {
  const baseDimensions = buildBaseDimensions(context, actionId);
  const createEvent = (statType, playerLabel, dimensions = {}) => ({
    id: crypto.randomUUID(),
    playId,
    playerId: playerLabel,
    playerLabel,
    statType,
    dimensions: { ...dimensions },
    time: timestamp.toISOString(),
    timeLabel: formatTime(timestamp),
  });

  switch (actionId) {
    case "SHOT":
      return deriveShotEvents(player, baseDimensions, context, createEvent, "shot");
    case "PENALTY":
      return deriveShotEvents(player, baseDimensions, context, createEvent, "penalty");
    case "SAVE":
      return [
        createEvent("SAVE", player.name, baseDimensions),
        createEvent(`SAVE_${context.height}`, player.name, baseDimensions),
      ];
    case "MISS":
      return [
        createEvent("SHOT_OFF", player.name, baseDimensions),
      ];
    case "TECH_FAULT":
      return [createEvent("TECH_FAULT", player.name)];
    case "STEAL":
      return [createEvent("STEAL", player.name)];
    case "BLOCK":
      return [createEvent("BLOCK", player.name)];
    case "CARD":
      return [
        createEvent(context.cardType === "YELLOW" ? "WARNING" : "CARD_RED", player.name, {
          card_type: context.cardType.toLowerCase(),
        }),
      ];
    case "SUSPENSION":
      return [
        createEvent("SUSPENSION_2", player.name, {
          duration: "2_min",
        }),
      ];
    default:
      return [createEvent(actionId, player.name)];
  }
}

function deriveShotEvents(player, baseDimensions, context, createEvent, shotType) {
  const events = [];
  const outcome = context.outcome;
  const shotDimensions = {
    ...baseDimensions,
    shot_type: shotType,
    ...(outcome ? { outcome: outcome.toLowerCase() } : {}),
  };

  if (outcome === "GOAL") {
    events.push(createEvent("GOAL", player.name, shotDimensions));
    events.push(createEvent("SHOT_ON_GOAL", player.name, baseDimensions));
    events.push(createEvent(`GOAL_ALLOWED_${context.height}`, "Goalkeeper", shotDimensions));
    if (context.assistPlayerId && context.assistPlayerId !== "NONE") {
      events.push(createEvent("ASSIST", playerLabelFromId(context.assistPlayerId), {
        target_player: player.name,
        shot_type: shotType,
      }));
    }
  }

  if (outcome === "SAVE") {
    events.push(createEvent("SHOT_ON_GOAL", player.name, baseDimensions));
    events.push(createEvent(`SAVE_${context.height}`, "Goalkeeper", shotDimensions));
  }

  if (outcome === "MISS") {
    events.push(createEvent("SHOT_OFF", player.name, baseDimensions));
  }

  if (outcome === "BLOCK") {
    events.push(createEvent("SHOT_BLOCKED", player.name, baseDimensions));
  }

  if (shotType === "penalty") {
    events.push(createEvent("PENALTY_SHOT", player.name, shotDimensions));
  }

  events.push(createEvent("SHOT", player.name, shotDimensions));
  return events;
}

function buildBaseDimensions(context, actionId) {
  const dimensions = {};

  if (context.height) {
    dimensions.height = context.height.toLowerCase();
  }

  if (context.location) {
    dimensions.location = context.location.toLowerCase();
    if (context.location === "FAST_BREAK") {
      dimensions.attack_type = "fast_break";
    }
  }

  if (actionId === "PENALTY") {
    dimensions.location = "penalty";
    dimensions.attack_type = "penalty";
  }

  return dimensions;
}

function calculateSummary(events) {
  const totalShots = events.filter((event) => event.statType === "SHOT").length;
  const goals = events.filter((event) => event.statType === "GOAL").length;
  const shotsOnGoal = events.filter((event) => event.statType === "SHOT_ON_GOAL").length;
  const keeperSaves = events.filter((event) => event.statType.startsWith("SAVE")).length;
  const warnings = events.filter((event) => event.statType === "WARNING").length;
  const penaltyGoals = events.filter(
    (event) => event.statType === "GOAL" && event.dimensions.attack_type === "penalty",
  ).length;

  return {
    goals,
    shotsOnGoal,
    keeperSaves,
    warnings,
    penaltyGoals,
    shotEfficiency: totalShots ? Math.round((goals / totalShots) * 100) : 0,
  };
}

function seedDemoSequence() {
  const demoEntries = [
    { playerId: "p9", actionId: "SHOT", context: { height: "HIGH", location: "FAST_BREAK", outcome: "GOAL" } },
    { playerId: "p10", actionId: "SHOT", context: { height: "LOW", location: "BACKCOURT", outcome: "SAVE" } },
    { playerId: "p7", actionId: "PENALTY", context: { height: "LOW", outcome: "GOAL" } },
    { playerId: "p5", actionId: "BLOCK", context: {} },
    { playerId: "p8", actionId: "CARD", context: { cardType: "YELLOW" } },
  ];

  demoEntries.forEach((entry) => {
    const player = players.find((candidate) => candidate.id === entry.playerId);
    const playId = crypto.randomUUID();
    const timestamp = new Date();
    const derivedEvents = deriveEvents({
      playId,
      player,
      actionId: entry.actionId,
      context: entry.context,
      timestamp,
    });

    state.plays.push({
      id: playId,
      gameId: "demo-game",
      time: timestamp.toISOString(),
      timeLabel: formatTime(timestamp),
      playerId: player.id,
      actionId: entry.actionId,
      context: { ...entry.context },
      sourceText: `${player.name} -> ${entry.actionId}`,
      label: `${player.name} ${entry.actionId.replace("_", " ")}`,
      contextTokens: Object.entries(entry.context).map(([key, value]) => `${key}:${formatContextOption(key, value)}`),
    });

    state.events.push(...derivedEvents);
  });

  render();
}

function loadPlayIntoEditor(playId) {
  const play = state.plays.find((entry) => entry.id === playId);
  if (!play) {
    return;
  }

  state.selectedPlayerId = play.playerId;
  state.selectedActionId = play.actionId;
  state.context = filterContextForAction(play.actionId, play.context);
  state.editingPlayId = play.id;
  state.currentStageIndex = Math.max(0, getFlowStages(play.actionId).length - 1);
  render();
}

function deletePlay(playId) {
  state.plays = state.plays.filter((play) => play.id !== playId);
  state.events = state.events.filter((event) => event.playId !== playId);

  if (state.editingPlayId === playId) {
    resetFlow();
    return;
  }

  render();
}

function playerLabelFromId(playerId) {
  const player = players.find((entry) => entry.id === playerId);
  return player ? player.name : playerId;
}

function formatContextOption(key, value) {
  if (key === "assistPlayerId" && value !== "NONE") {
    return playerLabelFromId(value);
  }

  return translations[state.language].optionLabel[value]
    ?? value
      .toLowerCase()
      .replaceAll("_", " ")
      .replace(/\b\w/g, (character) => character.toUpperCase());
}

function formatDimensionValue(key, value) {
  if (key === "target_player") {
    return value;
  }

  return translations[state.language].optionLabel[String(value).toUpperCase()]
    ?? String(value).replaceAll("_", " ");
}

function t(key, variables = {}) {
  const template = translations[state.language][key] ?? key;
  return Object.entries(variables).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

function setLanguage(language) {
  if (state.language === language) {
    return;
  }

  state.language = language;
  render();
}

function isMobileViewport() {
  return window.matchMedia("(max-width: 720px)").matches;
}

function formatTime(date) {
  return date.toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function filterContextForAction(actionId, context) {
  return Object.fromEntries(
    Object.entries(context).filter(([key]) => isContextEnabled(actionId, key)),
  );
}
